### ISSUE TITLE
Should not be able to place a RallyPoint in x meters of an enemy's secured objective

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#1005]
Having it so you can place a RP in enemy secured objective is sorta dumb and not only allows precapping, but sorta encourages it.

**Comment by kashash** [comment]
While we're at it I've also been a staunch believer that would benefit the game strongly if you also couldn't place RP in a friendly objective too. Because I've seen too many maps crumble and stagnate and overall go dull after impenetrable defences due to defenders simply spawning off inside the capzone they're defending. It destroys the whole purpose of trying to get back to the defense cap if you can spawn inside of it. Overall defence is too strong in DH and rally points is mainly the reason for it. There is most of the time no reason to put the RP outside of the cap so the players will always place it inside the cap in either bunker/building/trenches. If RPs were made so you can put only outside the cap whether it's friendly or not, I think it would improve the experience because it seems that it's not the maps fault that attackers are struggling but it's only when you have 3 squads in a team with 3 SLs that know what they're doing and all 3 of them have a rally inside the cap then it's impossible to conquer.

**Comment by kashash** [comment]
We have a restriction for HQs which is I think 50m from the nearest cap. And that range is perfect, any closer and it would be OP.

But I don't see any reason why not RP wouldn't also have this restriction, only that it wouldn't be as far as HQ which is 50m, but just anywhere right outside the friendly/unfriendly capzone. So it would still be a lot more advantageous than HQ.

**Comment by AndrewTheel** [comment]
What was done was Rallies cannot be placed in objectives you don't control.
