### ISSUE TITLE
Proposal to reduce the cooldown of the RP a little bit.

### ISSUE THREAD

**Issue by kashash** [DarklightGames/DarkestHour#1052]
I thought about writing this to see if you could agree to reducing the cooldown a little bit.

Whenever I run with the squad and very often you want to attack quickly, I constantly seem to have about exactly 28 seconds left for to put another rally. For me it feels like it's still too long and I often struggle to force to stay another player for 28 seconds and not move while I wait to put another rally.

If it was reduced perhaps by 5 seconds, then instead of that 28 seconds it would probably be around 23 which isn't that bad :D.

I also think it would benefit if the establishing time could be just shortened by 1 second at least.

I still think it's too long (for SL + 1 member) because half the time I get too far away and it gets abandoned without me even sprinting at all which kinda feels a bit annoying.

**Comment by AndrewTheel** [comment]
Okay so current values are:
NextRallyPointInterval=50 (after placing RP)
RallyPointChangeLeaderDelaySeconds=30.0 (after changing SL)
RallyPointInitialDelaySeconds=15.0 (after creating a squad)

The cooldown was mostly to combat potential exploits. The biggest exploit is using the RP as an enemy detector. We already have a separate timer for the squad SL exploit, which is actually must less than the NextRallyPointInterval time. And reforming a squad is dumb as hell, because getting everyone to change to the new squad is more a hassle than anything.

Based on how I see the situation, I think we'll end up shaving off 20 seconds from the NextRallyPointInterval in the long run (making it 30 seconds). However, I'm much for a cautious approach. Therefore I think shaving off 5-10 seconds would be ideal.

As for establishment time, I like exactly where its at. And I'm against lowering or raising it.

**Comment by AndrewTheel** [comment]
Oh, one idea I had to combat RPs being used as enemy detectors. If you place a RP and its quickly overrun by enemies (within 10 seconds). then it adds to a penalty to the NextRallyPointInterval (say 10 seconds). This will keep increasing for each one. It will go down for each spawn on a RP (-10 seconds per), when a reserve RP also exists.

**Comment by kashash** [comment]
Yes that could be good.
About the establishment, I just hate having to jog-slow run in order to not get the rally abandoned :P And half the time if I jog and the terrain is kind of sloped or not flat etc, then it's most likely it gets abandoned as well. So I just thought 1 second less would probably at least allow me to continue jogging and not worry about abandoning it. Whereas sprinting after placing rally would still abandon it anyway.
