### ISSUE TITLE
[Important feature] Target list looks like debugging info. Needs a visual facelift.

### ISSUE THREAD

**Issue by mimiski** [DarklightGames/DarkestHour#1275]
Target List:
![image](https://user-images.githubusercontent.com/56321463/121163030-bdaa7000-c84e-11eb-9b78-7e4a5da864de.png)

**Comment by mimiski** [comment]
@shiftycats 
Could you provide suggestions how to improve the target list's UI?

**Comment by shiftycats** [comment]
![](https://user-images.githubusercontent.com/36604408/93391923-99e66a80-f878-11ea-8488-e7208e6039c9.png)

**Comment by cmbasnett** [comment]
I think just having the text be slightly larger would be a big help. I think @shiftycats is working on some sort of target selection as well.

**Comment by mimiski** [comment]
The 'selected target' feature was rejected afaik

**Comment by shiftycats** [comment]
I don't recall rejecting it. It was the original plan to have it, but it kept being put aside because it was time-consuming to implement.

My experience with the target list during beta test was that it's largely useless in its current form.

The information it shows is meaningless to a player unless he's provided context (i.e. location of the marker on map and its surroundings). It's more natural to find the desired target on map first and "pin" its details to the artillery UI than do it the other way around. Players also need to figure out which "blimp" on the dial correspond to which target. 

Shrinking down the list to a single target will also reduce visual clutter and clean up the UI.

I'll do the work on the thing.

**Comment by mimiski** [comment]
As of 7df14b00b1304cb5795c6c1286d019b0f13c42fd target widgets look like this:
![image](https://user-images.githubusercontent.com/56321463/129796555-25da642f-6718-4a64-aa74-af7307509f19.png)
