### ISSUE TITLE
DH-Oosterbeek_Advance [Bug Report]

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1550]
- [ ] **-== Bug Description 1  /  DH Version: 11.3.0  /  Last updated: 24.01.2023  ==-**

- The wall of the building has a texture error, from one side it is transparent

![1](https://user-images.githubusercontent.com/123426586/214319635-49609116-29db-4fb3-bd82-0e11aabe526b.png)
![2](https://user-images.githubusercontent.com/123426586/214319660-97e896b4-ad2e-485a-a072-6b8e63b12253.png)

**Comment by GDrukenmiller** [comment]
Interesting, this is definitely a BSP bug. Maybe a map rebuild would fix it, but most likely this building (like most on Oosterbeek) was improperly made.

**Comment by DHFan45** [comment]
Thanks for the feedback.  Unfortunately, i don't know what "BSP" is.  However, it sounds like it would be a disproportionate amount of work to fix the bug, so it will not be fixed?

**Comment by DHFan45** [comment]
Thanks for the feedback.  Unfortunately, i don't know what "BSP" means??
It sounds like it would be a disproportionate amount of work to fix the bug, so it will not be fixed?

**Comment by GDrukenmiller** [comment]
BSP is the primary means through which we create buildings in the editor, unfortunately if not used properly it can break easily and cause these sorts of errors. It can most likely be fixed, but it's hard to say exactly what brush is even causing the bug. It could be simply the building the bug is presenting in has the error, it could be any number or combination of buildings anywhere else on the map, in which case finding and fixing them is not really worth it.
