### ISSUE TITLE
DH-Endsieg_Advance game hangs when loading the map

### ISSUE THREAD

**Issue by DHFan45** [DarklightGames/DarkestHour#1597]
### Describe the bug

The Game hangs every time when loading the map, the game must be terminated via the task manager

### Steps to reproduce

N/A

### OS

None

**Comment by Enfield-303** [comment]
Endseig will load.

Tested multiple times on my end, as well as tested on live during the beta test event, it does however require an extended time to load compared to regular DH maps

Please bear in mind that this is more than likely a localized problem due to the specs of your machine, endseig is a rather large map that is still in beta and requires far more optimization before being ready for live.
