### ISSUE TITLE
Mortar cannon pitch not correctly restrained and seems to desync in multiplayer

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#1737]
It's unclear why this happens but the pitch of the gun seems to desync and do a full 360 and then some.

Could be an "initial replication" type issue, although this is basically just a glorified AT gun so I don't know where it could be going so wrong.

Note here in the screenshot that the pitch is ~440 degrees. 440 - 360 is 80 degrees, which is a valid angle. Very weird stuff!

![Image](https://github.com/user-attachments/assets/fd864409-a0af-40ed-ba14-60b5012fd99a)
![Image](https://github.com/user-attachments/assets/f1ee80c8-d7b0-40c2-8ce7-00a0cb9b9b07)

**Comment by shiftycats** [comment]
Reproduction steps:

1. Start a server with 2 clients.
2. On client 1: build and mount a mortar on the opposite side of the map from client 2.
3. On client 2: approach the mortar.

**Comment by shiftycats** [comment]
The bug is caused by `overlay_in` and `overlay_out` transition animations being played on a net client by `SetPlayerPosition()` here:
https://github.com/DarklightGames/DarkestHour/blob/a7013f05b3f6c265350169ef266625fbb37ebf93/DH_Engine/Classes/DHVehicleWeaponPawn.uc#L2119
These animations have `pitch` bone keyframed in a raised position which messes up the rotation of the mortar tube.
