### ISSUE TITLE
M1A1 Thompson has bad geometry on rear sight

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#40]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

---

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/41

**Comment by handsm** [comment]
Re-opened as removing the specular maps from the weapons texture package hasn't changed anything, since the spec maps were't even being applied in DH 5.1. They weren't even related to the Thompson diffuse texture; they were spec maps for 2 smaller, unused, redundant Thompson textures. So the problem remains. If we did apply a spec map it would be exaggerated.

The geometry fix is - or would be - pretty straightforward. Problem is that the 'psk mesh file extracted from the anim file gets corrupted, with part of the player's arms missing. This is using UModel software to extract and I don't know any other way (there's no mesh export option in the editor). If we can find a way to get an uncorrupted .psk mesh out of the editor I can probably fix this quickly.

An odd thing is if I re-import the extracted, corrupted mesh back into the editor then the bad geometry on the sights (and elsewhere) is fixed, even when viewed with a super-shiny shader. It looks like the bad geometry got stripped away (or smoothed or welded or whatever) in the UModel extract process or the editor re-import.

**Comment by dynamittt** [comment]
I was having similar issues a week ago, and I contacted uModel author directly. I even invited him to a "live" demonstration how polygons vanish in thin air, but he did not seem very "interested" (or may be was simply busy since it was NewYears Eve)
Will do a follow-up when I have more information and time.
In the meantime I did load the Thompson mesh and anims and things are really screwed up.
I managed to fix the mesh (sleeves) but the bones need adjusting too and this requires time.
In the RoEd, open the mesh in the Animation browser.
Switch to Wireframe view.
You got some parts in red and other parts in yellow?
Expect problems!

**Comment by dynamittt** [comment]
I just checked my email and I got a reply from uModel Author - Konstantin Nosov aka Gildor
He did some research and confirmed one of my earlier doubts. The letter is in Russian and I will post his reply here after I have recomposed it in understandable English.

**Comment by dynamittt** [comment]
Original  letter (in Russian)
Привет.
Я поискал по коду UT2004 и кажется нашёл где выбирается красный или жёлтый цвет для SkeletalMesh wireframe. Красный цвет используется для "rigid sections" - это секции модели которые привязаны только к одной кости. Жёлтый цвет используется для "soft sections" - секции, привязанные к двум и более костям.
При загрузке некоторых моделей из некоторых игр возникают проблемы - эти модели сохранены с вырезанной информацией, которая используется в umodel. В движке они работают нормально, но в umodel - нет. Но такие модели обычно ПОЛНОСТЬЮ не поддерживаются - т.е. они не рисуются в umodel вообще. При этом в лог пишется сообщение вроде "bad mesh LOD" или что-то вроде того.

Translation by me:
"Hello
I have searched through UT2004's code and I think I found where the yellow or the red color for the SkeletalMesh wireframe view is determined. The red color is used for "rigid sections" - parts of the model that are weighted only to one bone. The yellow color is used for "soft selections" these parts of the model which are tied to one or more bones.
Upon loading several model from several games (for example mod for UT2004 etc. etc.) problems start to appear - these models are saved with information cut [from them - Dyn, interpretation], which is used in uModel. In the Engine they are working normally, but not in uModel. But these types of models usually are COMPLETELY unsupported - meaning they are not drawn in uModel at all. At which point in the log a message 'bad mesh LOD" or something close is written."
/_End of letter_

As I suspected, this was somehow related to how the mesh was done, but my PERSONAL opinion differs from Mr.Nosov's one a bit. When I was exporting original RO weapons I have seen similar problem only ONCE, and I guess the reason is the packages made by Tripwire are simply made "properly".
The most INTERESTING moment was that the mesh I was having problem with was partially rigid partially soft. (I did write the following in my first post in this Topic (but then deleted it because wasn't sure if the info was entirely correct)
"If you see parts of the mesh in yellow and parts of the mesh in red in the ROEd while using wireframe mode, then expect problems"
But then again, when I have exported meshes that are entirely yellow (soft) or entirely red (rigid) I have NEVER experienced any problems!
This is why I think problem comes not from missing information (like Mr. Nosov said) but is more likely caused by screwed up packaging upon import.
Again, this is my personal opinion based on my personal experience.

**I hope all of this information proves useful, and I will continue talks with 'Gildor' until a solution is found. Or at least until the reason for these issues becomes clear so that people avoid making similar mistakes.**

**Comment by handsm** [comment]
That's very useful, thanks Dynamittt. And Gildor looking into the problem - very nice! We owe that guy a lot really. It's given me an idea and I have a theory why we get the problem on some models, if not a solution:

'Soft' and rigid parts of the mesh are normal and unavoidable on a 1st person player model. The arms and hands have to be soft so they move like a human. For example, the parts of the mesh in the lower arm are assigned to both the wrist and elbow, and weighted between them, so that the lower arm is affected by rotation/movement of both the wrist and the elbow joints. Like you say, RO models are generally unaffected by this problem in UModel, and I think some other DH models are ok too. So it's only certain models - something to do with the way they have been made or saved.

Soft parts of the mesh are not necessarily affected by this bug. Notice that the player's hands are completely unaffected. It's only parts of the arms that go wrong. So what's different between the arms and the hands?

They are in a different material group for a start. The hands are material group 0 and get skinned by a hands texture. The arms are in material 1 because they get skinned by a different 'sleeves' texture. So, what's different about these 2 material groups?

The hands are in a material group that is completely soft. But the arms are a mix of rigid parts (some of the upper arms) and soft. So my theory is that the extract process will only accept a material group being either soft or rigid, not a mix of both. The hands are ok as they are just soft. But the arms material group gets treated as rigid, resulting in information about the soft parts being removed. At least the polys are lost, as the vertices all seem to be present, just not connected together to form polys. 

The RO models generally don't have mixed soft/rigid arms - the arms material group is all soft, which is what I'd expect. But you mentioned you'd found one RO 1st person weapon that got corrupted in a UModel extract. Which weapon is that? I am hoping to confirm my theory by finding it also has a material group that is a mix of soft and rigid.

If we can confirm that, maybe it will give Gildor an idea of how it may be fixed.

I don't think anyone will have any information about how old models were created. We don't have any of the source material, only what we can extract from the DH files. But I think it highly likely they were made using 3DS Max and exported using a Max .psk plugin, because that's more or less s standard way modellers work.

**Comment by handsm** [comment]
Might have a solution too! The mention of LODs gave me an idea. LOD is level of detail and I roughly understand the idea: an animation mesh file can contain several different versions of the model, at different levels of detail, i.e. number of polys. The idea is that when viewed from further away, a lower LOD mesh is used to save drawing too many polys for something small. The editor generates 4 LODs by default when you import a mesh.

Note that in a 1st person weapon model, different LODs are pointless, as the weapon will only ever been seen by the player carrying it, so always at point blank range. So since DH 6.0 all the different LODs in 1st person weapons have been removed, as that saves both file size and I'm pretty sure memory use, as previously the game was loading pointless extra LOD meshes that could never be used. This is not in any way related to the problem, it is just info.

When altering LOD sets in the editor, you have to 'redigest' them by pressing a button. For each LOD mesh you can specify an option called MeshSectionMethod. The options are rigid, smooth only (i.e. 'soft'), mixed, forced rigid, or single piece. I always use mixed as that seems to cover all parts.

So as an experiment, in the editor I set the current Thompson to smooth only only & ridegsted the LOD. This turns the whole model yellow in wireframe view, i.e. all 'soft'. Other options may well work (except mixed), but I thought soft had the best chance of preserving vertex data where the vertices are assigned to more than 1 bone.

Then I viewed in UModel and extracted the mesh. From a quick check only, it looks ok !  The arms are all there and they seem to move ok when animated. I have imported the modified .psk file back into the editor and the model looks and animates ok there too. And finally, in the editor I have changed LOD setting back to mixed and redigested - and the model returns back to a mix of rigid and soft (red & yellow) as it was originally. Note these changes are currently only on my own PC; I haven't uploaded any changes yet, as I want to check it properly. But very promising! :)

**Comment by dynamittt** [comment]
Amazing!! You nailed it Matt, and you were reading my mind the whole time. LOD is exactly what I was thinking about (redigesting) and then re-exporting-importing back to check. I am really sorry for not mentioning it, I wanted to try it first but since its working then I guess this is the 'current proper' solution.
The RO weapon that I found screwed is the 1st Person StielhandGranate24. The fuze pull-string is "soft" and was vanishing upon export!

And another tip: stay away from MilkShake software:  
http://www.chumba.ch/chumbalum-soft//forum/showthread.php?p=95729

> You will not be able to make 100% Correct PSK and PSA files with MilkShape because MS apporximatly saves the skeleton with predefined values (Wich may not be correct). Therefore i suggest, if you really like to use original as it ment to be, you have to use ActorX with 3DS MAX or Maya. I believe ActorX was used with 3DS MAX 5 for UT2K3. And ActorX works just perfect. Milkshape has a bug when it saves the skeleton because it hard coded fixes the rotation angle (which is wrong) and because of that you can not make PSK and PSA files correctly. Even Weights will be ignored, what makes your animation look more RIGID as it could be. ActorX is the only true thing. If really needed I could code you a converter that converts .MS3D to PSK or PSA error free, but I will not do it for free.

**Comment by handsm** [comment]
The RO German stick grenade confirms the theory: it's material group 2, which is the grenade itself, is a mix of rigid and soft parts. A weapon would normally be all rigid, just as a player's body parts would normally be all soft. But the stick grenade has a string attaching the base cap, which is animated when the grenade is armed. A string or rope is a relatively uncommon thing in game animation terms: it's a non-living thing that is soft/smooth instead of the usual rigid, because if the string/rope is animated it needs to move in a believable, fluid way.

And the fix works! As do simple model cleans to fix model glitches (in C96 as well as Thompson). Should be able to upload tomorrow.

**Comment by gildor2** [comment]
Hi guys. This is Gildor :)
Could anyone provide me a mesh which has mixed soft and rigid sections? I believe in my test I didn't find any when I worked with UT2004.
If that'd be possible, I'll fix the issue - of course if this will not break compatibility with other UE2 games.
It is very interesting that some project is depending on UModel :)

**Comment by handsm** [comment]
Hi Gildor - an honour, sir!

Here is the animation file for the particular weapon in this logged issue, the Thompson sub-machine gun:  [DH_Thompson_1st.zip](https://github.com/DarklightGames/DarkestHour/files/693268/DH_Thompson_1st.zip)

It is a 1st person weapon model, which is effectively a HUD overlay. It is by the 1st person player to give them a detailed, close up view of their weapon, including complex animations for reloading, etc. It includes the player's arms, to create the illusion that they can see their own body. In fact their player pawn's body is hidden from them and only seen by other players in 3rd person. As such, I would expect the arms and hands to be soft, with vertices assigned and weighted between two bones so the flesh moves smoothly, while the weapon would usually be rigid.

These 1st person weapon models usually have 4 materials groups: hands, arms & weapon. There is no problem if each material group is either entirely rigid or entirely soft. So a model containing both rigid and soft isn't unusual or a problem. It only becomes a problem when a material group contains a mix of rigid and soft.

The assignment of rigid and soft parts (red and yellow in the editor) in this model has been done automatically by the editor, on using the 'redigest LOD levels' option with MeshSectionMethod specified as 'MSM_mixed'.

It appears that all the vertices survive the UModel extract process, including their assignment and weighting to multiple bones. It is just some triangles that seem to have been lost, specifically the triangles formed from vertices in a 'mixed' material group that are assigned to more than 1 bone, i.e. the soft parts of that mixed material group. The triangles in the same group that are formed from vertices assigned to only 1 bone survive the extract.

I hope that is helpful, but please let us know if there is anything else we can provide or test. Many thanks for looking into this Gildor and good luck! :)

**Comment by gildor2** [comment]
Hi.
When I'm trying to open this mesh in UT2004 UnrealEd, it is crashed. Is this correct?

**Comment by handsm** [comment]
Problem with the Thompson's mesh fixed in commit https://github.com/DarklightGames/DarkestHour/commit/6575d3337cd3f834cca6dd3a94505a1b67833aad.

Now we have been able to extract the mesh, applying a simple model clean options fixed the problem. Below are a couple of before & after pictures, where I have temporarily applied a super-shiny specularity overlay, purely to highlight any flaws in the model:

This logged Thompson issue is now fixed and can be closed, but I will leave open a little way to continue working with Gildor.

![thompson_beforeandafter1](https://cloud.githubusercontent.com/assets/16405443/21771929/4d6cd90e-d681-11e6-9afe-dbd58b305ebe.jpg)
![thompson_beforeandafter2](https://cloud.githubusercontent.com/assets/16405443/21771936/50687046-d681-11e6-9fa9-d5b3de31c3bd.jpg)

**Comment by handsm** [comment]
Gildor - no, I would not expect the mesh to crash the editor. But then again, the editor is notoriously quirky and a goblin lives inside it! :)  And the editor we are using is a modified version, created by the game developer that published Red Orchestra, the game our free mod is based on. I understand it is closely based on the UT2004 editor but I don't have the original UT2004 editor and it isn't available to download through Steam, so I can't test it.

The animation file doesn't seem to require anything that would be loaded in the editor as part of our game. It does reference 3 texture files that you wouldn't have, but I wouldn't expect that to cause a problem, as if the textures don't exist the material slots just become 'none'. But just in case I have made a stripped down file version, with texture references removed and for good measure with the animations and mesh scaling also removed.

I've also included an Unreal .psk version of the mesh, which can be imported into the editor, in case my stripped file still crashes your editor (which sadly I suspect it will). The recreate the mixed rigid/soft material group I think you will need to use the redigest LOD levels options using 'mixed' for the MeshSectionMethod setting.

[Thompson.zip](https://github.com/DarklightGames/DarkestHour/files/693937/Thompson.zip)

**Comment by gildor2** [comment]
I'm glad that you fixed the issue internally.
Well, anyway - I've made a workaround for such meshes. It is very hard to fix this issue correctly (it requires a lot of coding), so I'm detecting when a mesh has both soft and rigid sections, and not using LOD resources for them anymore - I'm using pure editor's data. UModel will display a message in log that LOD can not be used, and will switch to a different code path.

**Comment by dynamittt** [comment]
Great news, I think this topic will contribute not only by solving this specific issue, but to the whole Unreal-based modding community.
Guys please note that UnrealEd and ROEd have _at least_ one difference, the UnrealUnits to Meter conversion.
 @**gildor**, I can upload the ROEd on a Russian based server for you to download if need be, but not today.

**Comment by handsm** [comment]
Thanks Gildor. Glad you could fix it - and such quick work too! Cheers. :)

I'll close this Thompson issue now, but ppls can still add comments here if need be.
