### ISSUE TITLE
Artillery and mortar explosion emitters do not spawn if the player is not looking at it

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#407]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

----------------------------------------

Title says it all. Have suspected this to be the case for years, but finally confirmed last night.

----------------------------------------
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/408

**Comment by handsm** [comment]
I have subsequently done a lot of investigation & fix work on the general issue of when effects are culled, which is all about the function EffectIsRelevant(), which I now understand very well.

Whether or not to spawn the effect is based on a distance check. If the effect would be boradly in front of the player, and so would appear on their screen, a normal distance check is used, i.e. effect only omitted if relatively far away.

But if the effect would spawn to the side or behind the player, then a short distance check is used - 1600 UU or 26.5m by default. The logic being that although the effect location won't be on the player's screen, things like flying debris may well pass into the screen view.

The function calculations were bugged for anyone in a vehicle - now fixed in various classes, including all shells & other projectiles.

A crucial point is that sound effects should not be under an EffectIsRelevant() check, either directly or because sounds are in the effect class. Sounds must play regardless of direction and the engine will attenuate the volume according to distance. So an explosion sound must be played even if the visual effect is omitted.

**Comment by cmbasnett** [comment]
Changed the title of this one because this is now affecting mortars as well in 6.0.

**Comment by handsm** [comment]
It would be easy to remove the standard EffectIsRelevant() check that sometimes stops the visual explosion effects if the game doesn't think the player could see it. But what's the exact issue here?

The explosion sound should be playing regardless of view direction - I assume it is, correct?

If the player isn't looking at the explosion, the visual effect should still spawn if it's within about 25m. I think that's so any showering debris

**Comment by handsm** [comment]
It would be easy to remove the standard EffectIsRelevant() check that sometimes stops the visual explosion effects if the game doesn't think the player could see it. But what's the exact issue here?

The explosion sound should be playing regardless of view direction - I assume it is, correct?

If the player isn't looking at the explosion, the visual effect should still spawn if it's within about 25m, presumably so any showering debris that may cross the player's screen from the side will get drawn. Is it just that some explosions are big, so the 25m side cull distance isn't sufficient, i.e. the player is close enough to get rained with debris, but doesn't see any?

If it is that, then suggest we retain the EIR check, but I'll up the side cull range for big explosion effects. Probably add a range variable that can be set per shell if desired. Maybe auto-calculated from blast radius or some other measure of the shell's power.

**Comment by AndrewTheel** [comment]
Mortars are always relevant, so you mean if you have a mortar fall down behind you and then you turn around you don't see anything?

**Comment by cmbasnett** [comment]
Correct. Mortar explosions should always be relevant to spawn on the client. This direction-based relevancy check really is a pointless optimization and I find myself irked by the fact I can be damaged by a mortar falling behind me only to turn around to find there's no explosion emitter. Recommend we remove this EffectIsRelevant check on mortars.
