### ISSUE TITLE
Many vehicles have destroyed static meshes that do not match their camouflage pattern

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#469]
Originally reported by: **Colin Basnett (Bitbucket: [cmbasnett](http://bitbucket.org/cmbasnett), GitHub: [cmbasnett](http://github.com/cmbasnett))**

---

This can be a 7.0 task. It's part code, part asset management. Will fill in with more details later (specific examples etc.)

---
- Bitbucket: https://bitbucket.org/darklightgames/darkesthour/issue/470

┆Issue is synchronized with this [Trello card](https://trello.com/c/nIQLDMi6)

**Comment by handsm** [comment]
This is an old issue, not assigned to anyone. It's probably redundant now, but I'm going to be adding some destroyed skins for the new Soviet vehicles, so I'll review if any other destroyed skins (combiners) are needed.

**Comment by handsm** [comment]
In commit https://github.com/DarklightGames/DarkestHour/commit/40a28fe26ec990df8b82b51ade0728077e22b910 I've done a thorough review of all destroyed static meshes and skins for all vehicles and AT guns.

There is now a suitable destroyed static mesh for every vehicle and AT gun and all camo variants, or destroyed combiner skins that are used to re-skin a static mesh. There's also a destroyed combiner skin for all treads.

All of these now use the DH style destroyed combiner skins, using Peter's destroyed effect overlay textures with the undamaged skin, so all destroyed vehicles and guns have a consistent look. This includes several German vehicles that were using an RO destroyed mesh style that had a blackened, generic look, that was used for several camo variants. That generic approach was handy and saved lots of separate static meshes. But since we use the combiner technique and also have the DestroyedMeshSkins array to re-skin statics, there's no longer any advantage, and these RO statics jarred visually with other vehicles. 

RO skins replaced are for the German halftrack, panzer III and IV, panther, tiger and 88mm flak. Also new destro skins for: 88mm flak camo variants, base jagdpanther, panzer III3N camo2, panzer IVG and J camo variants and German HT camo3 & 4. New winter destro skins for: Wolverine, Sherman M4A3 75mm & 76mm turrets, 88mm flak, kubel and tiger.

New destroyed static mesh for Cromwell 6 pounder (was using the 75mm version).

Modified Jackson destroyed static mesh to put the muzzle brake in a separate material slot, so now works for both the early and late versions (early version simply hides the muzzle brake).

Corrected destroyed static mesh used for Sherman M4A3 76mm, as the static previously used had a muzzle brake while the tank does not.

Also added DH combiner destroyed skins for future Soviet vehicles, e.g. BA64 armoured car, T60 tank, KV1 tank.

Note that for winter vehicles, the ones that only have a snow topping on a summer/autumn camo pattern don't generally use a winter destroyed skin. The primary purpose of these destroyed statics is to represent a destroyed vehicle, which is usually in a blazing fire, so any snow would melt pretty much instantly, leaving the normal camo paint underneath. On the other hand, whitewashed vehicles do have their own destroyed skins because that's a paint job.
