### ISSUE TITLE
Some tank drivers can see through the tank when transitioning positions, e.g. tiger

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#485]
![2015-12-26_00034](https://cloud.githubusercontent.com/assets/5035660/12009237/e266b7ec-ac24-11e5-8fe2-a26858fa2b50.jpg)

**Comment by cmbasnett** [comment]
The issue here is that the view rotation bounds of the driver immediately becomes the rotation bounds of the position being transitioned into.

**Comment by handsm** [comment]
Easy to modify view limit functionality so that the limits of the new position are only applied after transition is completed. But may then cause problems in reverse, so need to work that through and consider different situations where it may be a problem.

Best solution may be to use the most restricted view limits of either the old or new position, during the transition. But again need to work through how that would manifest across a range of situations. And it's in a many-times-a-second function, so the implementation needs to be clean and optimised.

**Comment by handsm** [comment]
Affects quite a few tanks to a greater or lesser degree. Tiger, panther and T34 are especially bad. Have fixed, will commit soon when separated out various code work.

**Comment by handsm** [comment]
Mostly fixed in commit https://github.com/DarklightGames/DarkestHour/commit/5b0ac02230528c4c95425c014fbd344ea4ce6d51.

When driver is in the transitioning state, we now simply use the lower of the yaw limits for the old and new positions. The LimitYaw() function actually ends up shorter and simpler as it wasn't using Clamp() to restrict yaw limits, instead doing a manual version of that. So now when the driver unbuttons, his view yaw remains restricted to the smaller yaw limits of the buttoned up position, and is only relaxed to his new, wider unbuttoned view when the transition completes.

Fixes the problem entirely for a range of vehicles that suffered from this problem slightly. And makes it far better for vehicles that had big problems, like the tiger, panther and T34. But a couple need a slight further tweak by slightly reducing the buttoned up view yaw limits (or editing the interior models to give them deeper internal side walls), which is quick and I'll do next.

This is needed because the current buttoned up yaw limits are ok for the static buttoned up camera position, but in some vehicles the camera slides backwards a little as the player unbuttons, and then the view yaw maximums display a small bit of the unmodeled interior.

**Comment by handsm** [comment]
Fix in commit https://github.com/DarklightGames/DarkestHour/commit/aec912b8ed6d322791180d82a4bea52fdfd81d21 for problems with remaining vehicles.

Checked all vehicles and only remaining problems are with the tiger and panzer IV ausf. G.

I've edited the internal hull animation mesh for both tanks, which are the RO models. I've added or extended hull interior sections to the side of the driver so he can no longer see through any part of the hull when unbuttoning and the camera position is moving.

I've also closed up various other holes or gaps in the hull, which the driver could see through when transitioning up, regardless of view limits. These models had been made so the view was all ok when the player was buttoned up, but did not take into account the raising camera position when the player unbuttoned.
