### ISSUE TITLE
Some players do not rag-doll when killed and their bodies stay around as "zombies"

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#494]
The zombie bug appears to be happening randomly.  I believe it has something to do with the species not being set and or the karma rag doll not being set.  This is likely because of one or more of the following reasons:

1) MattUKs changes to how the species is set and/or changes to the species (I remember him doing something in this nature)
2) Our spawning system and this could (and likely) be related to the wrong uniform/skin bug
3) Pre-caching changes

**Comment by cmbasnett** [comment]
In 5.0 (not 5.1), this happened because the German sniper role had some sort of incongruency between the "species" defined directly or indirectly on the role. This would also throw a console error up whenever this happened. I'm guessing that whatever recent species changes re-manifested this bug. It's entirely possible that it's 100% reproducible on certain roles.

**Comment by AndrewTheel** [comment]
I noticed it happen a couple times as Combat Engineer, not sure which map/side though.

**Comment by AndrewTheel** [comment]
I have not seen this or heard complaints about this in awhile, so it was either solved or happens so rarely that we need to know more details to solve it.
