### ISSUE TITLE
Non-exposed tank commanders can appear above the tank with their arms in the air

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#498]
I swear this bug has been reported and "fixed" before, but it appears to have made an appearance. This might be specific to just certain tanks. I only recall seeing it on the Panther on two separate play sessions.

I'm quite certain this only happens when the tank first becomes network relevant.

![2015-12-29_00004](https://cloud.githubusercontent.com/assets/5035660/12048512/d993c542-ae90-11e5-8495-07423628b794.jpg)

┆Issue is synchronized with this [Trello card](https://trello.com/c/JNB30SkO)

**Comment by handsm** [comment]
Some additional info reported in a duplicate issue:

Saw an enemy tank approaching: tank commander's hatch was open but there was nobody inside this position: the attempted "whack-a-mole" shot yielded no result. After couple of seconds, driver switched to tank commander's position (I could see this using my binoculars) and commander's hatch no longer appeared to be open! Another thing I noticed: sometimes shooting at an open hatch will result in a blood-puff emitter being shown and a kill scored on the commander, no matter if no head was visible!

**Comment by handsm** [comment]
I haven't seen this problem for some time. It was reported a long time ago ad there may have been changes since. Does anyone know if it's still an issue?

**Comment by cmbasnett** [comment]
There has been inconsistencies that I notice with the system, but it's hard
to point at anything specific. I generally trust that shooting a commander
or driver will work as intended barring any of the occasional impression
that the shots aren't registering.

Weird things do happen however, like a commander being popped out of his
hatch and then immediately being gone; perhaps they are switching
positions? This might be something we should disallow: to switch to another
internal position (driver, hull etc.), the hatch must be closed. What's
your take?

**Comment by handsm** [comment]
Well, the reported bug is specific and was certainly prevalent in DH v5.1, I think only in multiplayer. I believe it's a problem with a net client not getting the player attached correctly to his attachment bone in the turret rig, or not attached with the correct positional offset. In the picture it looks like the commander is unbuttoned, but it also looks like the hatch is closed, so I believe he is actually buttoned up. If so, the client has the player in the correct pose, with arms above his head at the start of the unbuttoning transition animation, ready to open the hatch - but does not have him in the correct position. In that scenario you could appear to shoot the commander, but no damage would be done because he's really buttoned up.

Some time ago I added network timing fixes that I believed had worked around problems like this. Specifically in this case, I added a bNeedToInitializeDriver flag for a net client that received a vehicle or vehicle weapon actor via actor replication that had an occupant, which then triggers a SetPlayerPosition() function when the client has received the required player and vehicle/weapon actors. That includes a re-attachment of the player in the correct position, so I believed it had solved the problem.

Your point about a commander disappearing immediately is a good one. And yes, that will be when he switches to another internal vehicle position, i.e. driver or MG operator. I agree it would be better and more realistic if he had to button up to do that. I don't think it would be hard to implement.

We're getting off the original issue here, but on the same subject as the point you raised, I've been thinking it would be more realistic and plausible if a player entered a vehicle position in the unbuttoned position. So if you get into a commander's position, you would be unbuttoned and exposed, rather than materialising on the gun. Same with the driver. MG positions in most vehicles become a problem there, as a significant failing in most of our tanks is the MG positions don't have working hatches.

**Comment by cmbasnett** [comment]
Going to close this one since it's obviously long been fixed. Another separate issue can be made for requiring commanders to be buttoned up in order to switch positions, as I think that's quite sensible.

**Comment by handsm** [comment]
I haven't seen this in ages, but I suspect similar vehicle occupant attachment bugs can occur very occasionally.

What made me think this was a friend sent me a screenshot of what appeared to be a buttoned up tiger driver with his left arm poking through the left side of the hull, between the sponsons and the wheels. He thought it was a positional attachment error in the set up (default properties) of the tiger, resulting in a **_horizontal_** positioning error.

But the setup is fine and I noticed the driver's hatch was open, so actually what we were seeing was an unbuttoned driver that was considerably lower than he should have been, resulting in his bent left arm from the unbuttoned pose poking through the hull. It was actually a **_vertical_** positioning error.

The vertical error was about three quarters of a metre and it looked suspiciously like the Z +42 offset from a DHPawn's 'PrePivot' vector, which is supposed to be applied when the player pawn gets attached to a vehicle position (along with any DrivePos positional correction in the vehicle class). I used the SetDrivePos debug exec to simulate this error by changing the DrivePos on the tiger to Z -42. And yes, this perfectly re-created the tiger bug screenshot, confirming that a faulty attachment missing the PrePivot offset.

I cannot see how this happens though. I first thought it was because the server zeroes the PrePivot immediately after attaching the player and PrePivot replicates to clients. So I thought if the zeroed PrePivot had replicated very quickly then when AttachDriver() gets called on the client is may perform its own attachment incorrectly using the zeroed PrePivot. Made perfect sense and wouldf have been fixable - but AttachDriver() uses the **_default_**.PrePivot and the default never gets changed, so I'm really at a loss as to why it goes wrong.
