### ISSUE TITLE
Round should go into "overtime" if players are capturing the last objective after the time runs out

### ISSUE THREAD

**Issue by magicdutchman** [DarklightGames/DarkestHour#505]
Not sure what has happend with the overtime, but I hope you guys bring it back.

**Comment by cmbasnett** [comment]
I'm not sure what you mean by overtime. Rounds have always ended when the time runs out.

**Comment by magicdutchman** [comment]
Overtime in a sense that the round continues runs out during the event that an objective is being captured.

**Comment by cmbasnett** [comment]
As far as I know, this was never a feature of either RO or DH. It is however, something we can consider for a future update. I will mark this as an enhancement.

**Comment by magicdutchman** [comment]
I might be mixing it up with RO2. If I do, then that might be one of the few improvements in the newer title :-P

**Comment by dynamittt** [comment]
I don't agree with this, since it will give the attackers an ultimate advantage if defenders' reinfs have ran out!
You either cap in the time you get or you lose.
OR only give overtime if attackers have already STARTED capping the objective, AND they have capped more than 50 percent of it.

**Comment by cmbasnett** [comment]
I believe the idea was that overtime would only be initiated if a capture of the *final* point was already in progress.

**Comment by dynamittt** [comment]
Yes, I am aware of the idea and it is exactly how the RO2 overtime works. Now the cons:
Such scenario would give the attackers ultimate advantage in case defenders reinfs. are zero., because, by the time the capturing of the final objective has been initialized, chances for them to successfully defend it are none. Right now, without overtime, defenders often manage to hold the final objective even if they have been without reinforcements for some time. 
Defenders' reinfs 0 + overtime = almost 100 percent guaranteed victory for attackers.
Defenders reinfs 0 w/o overtime = FAIR chance for defenders to hold the final objective.
If time is up, and defenders are out of reinforcements for some time, its very likely that some of them have already been killed. Meaning that they already have less alive players than the attackers.
Meaning that even if their whole team was inside the cap, they cant hold it against full attackers team.
OR
Attackers manage to get into capzone in the last seconds, and overtime is added. But attackers will always win in this scenario, because chances that defenders without reinforcements have their whole team alive are very low. And even if this is the case, a SINGLE death means immediate capture progress in favor of the attackers...and inevitable victory for the attackers.

May be, add overtime only if both teams have reinforcements over zero.
If defenders have allowed attackers to initiate a capture of the final objective, even though they have plenty of reinforcements, why not give overtime?

**Comment by magicdutchman** [comment]
Wow...I didn't think this idea would create such a huge discussion. Either way, I think overtime creates an intense addition to the gameplay that is easily modified. And let's face it...when you're halfway on the final cap as an attacker and lose because of the lack of time. It's a huge letdown.

**Comment by AndrewTheel** [comment]
This all just complicates things, and really doesn't offer any sound benefit.  Does the time added repeat, does the attacker lose immediately if they lose foothold in the cap?  If time is just set to infinite and the winner is defined by the outcome of the capture, why isn't each capture like this?  Why only the last one?  If it just adds say 1 minute or 2 minutes, does that repeat each time attackers are still in the capture, if so then if some guy is say in a tank and enemies have no way of killing it, then the map will never end.  Again needlessly complicated, the idea of push is to have it time based, not time based until you get to the last capture.

Personally, I'm not for adding a overtime system, it'll just seem like a bug because we haven't had it in for so long.  Regardless of who gets the benefit of overtime, I'd rather this be some sort of player driven ability than something automated.  Where say a commander requests more time, or players can vote to extend the level.

**Comment by cmbasnett** [comment]
After some discussions amongst the team, we've decided against adding this. It creates a lot of complicated design considerations we have to work around, and the payoff for implementing such a feature really isn't worth the effort.

Closing and locking.
