### ISSUE TITLE
Anti-tank rockets should be assist-reloaded when deployed and resupplied by a teammate

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#542]
Very annoying to be resupplied by a teammate while deployed and then they don't hit the button a second time and you have to reload manually. We'll roll this all into one action.

**Comment by dynamittt** [comment]
I have always liked the original idea behind reloading these AT weapons, but I would like to make a serious realism-based suggestion:
Reloading these types of launchers used to take reasonable amount of time **even** if they were used by a crew of two.
Rocket had to be inserted into tube, positioned properly inside, then a pair of wires are extended from the rocket and are connected to special to a pair of contacts located on the back side of the tube.

What we have right now is player presses a button and the weapon is assist reloaded immediately, while it should take some time, and both of the people operating the weapon should have their hands completely free. Meaning they are not able to do anything else.

So what I suggest:
Add the following limitations:
Re-usable anti-tank rockets depicted in the mod
 can be reloaded by a single person or a crew of two (ideal conditions).
They can only be reloaded or assist-reloaded while both of the crew-members are staying still, and not moving.
**And this is the time to mention that "assist-reload" is wrong term, since the weapon is originally made to be used by a crew, not a single operator.**
The crewmember who is reloading, should holster any weapon he is currently holding, since both of his hands are occupied with aligning the rocket and attaching the wires.
_This can be done automatically, since it will be kinda bad to force players to manually do something else before attempting to reload someone's Bazooka or Schreck._

After the reloading sequence has begun, both players will receive a LocalisedMessage saying that reload is in progress. 
The moment reloading is complete, the crewmember who was reloading gets a Message saying that the Reload is done, and the weapon he was previously using is brought up in his hands. 
He can now move freely.
After he moves away from the back end of the tube, while remaining in close proximity to the operator, he can give a "GO/FireAtWill/Clear" call, telling the operator that the weapon can be fired (to simulate tap on the shoulder or voice command).-Localised Message is displayed on the operators HUD.
_If he moves too far away or dies after a complete reload, the "GO" call is given to the operator automatically._
_Or alternatively, after a successful reload, after a certain amount of time (2-3 seconds), if the operator fails to acknowledge,  the "FireAtWill" call is given to the operator automatically always, so that he knows he can fire._

And the final suggestion: increase time needed for a lone operator to reload , and of course make it possible only if player is standing still(as said above), **BUT allow a crewmember or another soldier to join in and assist the reload in progress, leading to faster reload.**

Criticism:
The way the current mechanic works combined with the short reload times forces operators to play "bravely" and to attempt reckless and unrealistic approach when it comes down to disabling/neutralizing enemy tanks.
The realistic approach would be:
Concealment is number one priority, because after taking a shot you never get a second chance: position is compromised by the smoke and dust, immediately drawing enemy's attention to your position. This can be brought to the attention of the players by making the reload times faster.
We will no longer see players wielding Bazooka/Schreck pop in an out of cover to take a shot and get an immediate reload by their crewmembers.
With the current mechanic, you can line 5 rifleman behind a wall, and a single operator can fire 10 rockets in less than a minute, by being "assist reloaded".
 
Players will use ambush tactics, rather than just engaging tanks head-on at medium and long range.

Overall improvement of gameplay and CA firefight balance, bringing realism closer while still leaving the Tank-Hunter class playable by the vast majority of players can be achieved by bringing in elements of realism and at the same time avoiding harsh unneeded limitations , like for example allowing the weapon to be reloaded by a full crew while in IS and out of IS, and even while prone.

Another critical (completely irrelevant to the above) discussion must be initiated, to discuss the weapon itself and its penetrating capabilities. (M6 rocket used in the M2 launcher and HEAT rockets used with the PanzerSchreck).
The reason is simple: Different types of warheads existed for both of the weapons(Shaped-charges, HEP and HEAT).

Thank you for your attention.
https://www.youtube.com/watch?v=IRPsxgOozqk

**Comment by cmbasnett** [comment]
@dynamittt Yes, in this change we'd also like to increase the amount of time it would take to reload to "assist reload" the weapon. Right now it's a little less than a second. The easiest way to offset the proposed change is to increase that to about three times. All it means is increasing the duration of the animation.

**Comment by cmbasnett** [comment]
Fixed in commit 4ad02f7dd50fcd45661858296ff49786eb64ddcf. The solution we settled on was to increase the time it takes to receive an assisted reload by increasing the duration of the associated animations.
