### ISSUE TITLE
Melee hit effects create a bullet hit effect/sound instead of just the melee hit sound

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#553]
This crept in a commit that I suspect MattUK did, assigning to him to investigate.  Basically this is the same issue in Arma2/DayZ where melee weapons create a ricochet sound, we are casually calling it the "Ricochet Fist" bug, from that hilarious DayZ video.  (https://www.youtube.com/watch?v=7zlVAGIhC2M)

**Comment by handsm** [comment]
Fixed in commit mentioned above. 

What, didn't like my DayZ flavour to the game? :)  One of those cases where you fix one bug & find another.

But, this has been a very useful, temporary bug, because it has shown that melee hits cause unnecessary hit effect replication to all new clients, when no hit visual effects are going to be played.
So I've been able to remove the offending code & optimise the network.
