### ISSUE TITLE
Players should not be able to spawn into burning deploy vehicles

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#571]
We have checks to prevent players from entering a burning vehicle, but we allow them to spawn on DVs that are on fire.  I think once a DV is on fire it should no longer be considered a DV.

┆Issue is synchronized with this [Trello card](https://trello.com/c/VtYNa0X6)

**Comment by cmbasnett** [comment]
There's two parts to this. The first part is that there need to be a `bOnFire` bool in `DHVehicle` that I can check to block spawning . Currently, it only exists in `DHArmoredVehicle`, which the half-tracks don't extend from. Passing this over to @handsm; when the functionality has been moved up the hierarchy, let me know and I'll take over.

**Comment by AndrewTheel** [comment]
Actually all one needs to do to fix this is to rip off the vehicle from the spawn vehicle array in DHSpawnManager when the vehicle is lit on fire.  As currently there is no way to put out a fire, if an extinguisher is made, then we will need the bOnFire bool.

**Comment by handsm** [comment]
I think this is caught up in other, broader issues logged about changing the fire code.

But an implementation of this specific change should actually be very simple, without needing to touch the fire code at all. Fires for non-armoured vehicles are very crude and basically if the engine health falls to zero a fire effect is shown on the engine and the vehicle can't be driven. There is no progressive fire spread of vehicle destruction, just a burning engine. For APC vehicles, this actually happens when the vehicle's health falls to one third of max, which I think is original RO code designed to give the occupants time to bail if the APC is hit and badly damaged but not destroyed.

A simple EngineHealth <= 0 check on a non-armoured vehicle should do it. Leave it with me. I'll add a v8 milestone as this should be a quick thing.

**Comment by handsm** [comment]
Fixed/implemented in commit https://github.com/DarklightGames/DarkestHour/commit/bc818334b50a449f0dd770cdd270cf8b4f48dfa8.

I've added an IsVehicleBurning() helper function in the vehicle classes. In DHVehicle it returns true if EngineHealth is zero or less, which is when a non-armoured vehicle (like pretty much any spawn vehicle) spawns the engine fire effect and can no longer be driven. In DHArmoredVehicle it is subclassed to use the sophisticated vehicle fires system and returns true if bOnFire or bEngineOnFire.

Have substituted the new function into various vehicle code to replace use of same bool checks, but it's main purpose is to facilitate a vehicle burning check in the DHSpawnPoint_Vehicle class's timer function.
I've added a new spawn point BlockReason called SPBR_Burning, which gets set by a simple Vehicle.IsVehicleBurning() check in the timer.

Have re-factored the timer function so that (1) it returns if it finds any blocking condition and set the BlockReason (where before it would continue to check all blocking possibilities and a later one could overwrite another), and (2) so that it checks in a deliberate sequence where the most important/long lasting blocking reason is checked first and takes priority over any others, then works down the list.
For example, the spawn vehicle burning is no.1, as that means the vehicle can never be spawned into again, then parked in an active cap zone is no.2 as it requires significant intervention to resolve, then enemies nearby is no.3, as it could just be one enemy who may die or depart any time, and finally vehicle full is no.4 as a player could exit at any moment.
