### ISSUE TITLE
American and many other vehicles have destroyed static meshes with overbright treads

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#578]
![20160610195405_1](https://cloud.githubusercontent.com/assets/5035660/16169085/41a4b918-34d6-11e6-8fba-c61529b714ba.jpg)

This is because I never made overlays for the treads, probably out of lack of time. This will take a while to fix completely because all the destroyed statics will need to be updated. A good two hours of work at least.

**Comment by cmbasnett** [comment]
Going to close this as this is probably never going to be addressed.

**Comment by handsm** [comment]
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/40a28fe26ec990df8b82b51ade0728077e22b910.

Added destroyed skins for all treads. All using DH style of making a destroyed skin combiner from the original skin and one of the destroyed effect overlays. Works pretty well on treads, darkening them and grubbing/scuffing them up.

Applied to every tracked vehicle in the game, either directly in a specific destroyed static mesh, or by adding to the vehicle's DestroyedMeshSkins array, which re-skins the static mesh, e.g. where an RO static is being used.
