### ISSUE TITLE
Abnormal Vote Menu Wait

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#579]
After a map has been voted to swap teams and restart, the wait time on the second vote seems to be much longer.

**Comment by handsm** [comment]
See issue https://github.com/DarklightGames/DarkestHour/issues/584 (server can end up 'jammed' & players can't join a team). Could be the same or similar issue; may even be fixed.

That critical problem was caused by the GameInfo's bGameRestarted bool being left true by the 'swap teams & re-start' option. The apparent fix has been to reset it to false.

**Comment by AndrewTheel** [comment]
I'm pretty confident this is the same issue, but instead of seeming like a very very long wait time it just wasn't counting down and what changed the map finally was enough votes for one map.
