### ISSUE TITLE
Texture loading issue in Hurtgenwald

### ISSUE THREAD

**Issue by kuopassa** [DarklightGames/DarkestHour#582]
Happened 28th June in Hurtgenwald when some textures were missing from a pile of trees. Here:

[As seen here](https://youtu.be/hSphkwfOHb0?t=45s)

**Comment by AndrewTheel** [comment]
There is nothing wrong with that texture, that map, or otherwise the game.  Unless you know a way to consistently get this to happen, I'd say it is a rare bug that happens between the game and hardware rendering.  Though I've never personally had this happen to me.  Obviously this type of issue could be considered an exploit or even cheating, so if you know of a way to recreate it, please personally contact us via steam message or email: info@darklightgames.com
