### ISSUE TITLE
Graphics Bug?

### ISSUE THREAD

**Issue by BeLL123** [DarklightGames/DarkestHour#583]
Hey Darkest hour its me BeLL I play a lot of dh and I felt I should address this issue. I'm not sure if this is from the new update or on my end. but I recently was in the middle of a game and flipped my shut off switch on my power strip and then when I relaunched Darkest Hour I noticed I had to reset all of my button commands because there were none and then when I go to see if my graphics are fine I had to reset them too and this is where I'm having a problem... I click on custom settings and i click show advanced settings and i can change the advanced settings but when i click back and click display settings again the Show Advanced Settings box is not checked and i can not get the box to stay checked and i feel as if its not checked its not using my advanced settings.. i have tried reinstalling steam and darkest hour.. and i noticed the box stays checked in my other red orchestra games and mods. is there a way i can fix this you is it because of the new update

**Comment by handsm** [comment]
Hi BeLL. I don't believe there's a problem and your graphics settings should work fine. Nothing has changed; the situation you describe seems normal and your custom/advanced settings will take effect. It is exactly the same as in RO, at least it is for me. I have just started RO and clicked 'show advanced options' (SAO), then when I go back into the display settings that box is not checked, the same as you describe in DH.

When you select one of the pre-set graphics levels (low, high, etc), the advanced options are greyed out. As soon as you select custom settings mode, either by directly selecting the custom option or by clicking SAO  (both do the same thing), the advanced options 'light up' and are usable. Then when you go back in to the display screen, the SAO box is not checked. You can check and uncheck it, but it no longer does anything and you can't get that box to stay checked. Doesn't matter. The bottom line is that once you go into custom detail mode, the advanced settings window is active and those settings work, and the SAO box becomes irrelevant.

Like I said, this is the same in RO. It's probably a poorly designed interface screen, because the SAO box seems irrelevant and unnecessary. It should probably only have the custom detail option, from the drop down list, which would not cause confusion.

You said you feel that your settings may be being used if SAO is not shown as checked. Have you tested this? Just change one setting to something that would give a very noticeable difference, then go into a level in single player. If you see the change, then it's fine. A good test is to change 'texture detail' to 'very low' - you'll see that straight away.

**Comment by BeLL123** [comment]
yea I didn't try texting to see if it made a difference but I just checked settings from low to high in a map and it seems to still work it just threw me off a bit and I see in mare that the box stays checked I guess its just me lol thankis though I'm glad you addressed me issue I am very happy about this new update and the graphics that's why I was disappointed when my computer reset and everything was wiped I didn t notice the uncheck box until I crashed and its just a normal thing so no need to worry I guess thanks

**Comment by BeLL123** [comment]
testing^

**Comment by handsm** [comment]
No problem.
