### ISSUE TITLE
RPG43 grenade explosion should have a different sound

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#609]
The RPG43 grenade has the same explosion sound as the PTRD firing sound. We should have a unique explosion sound for this.

**Comment by handsm** [comment]
I hadn't noticed this issue, but when I overhauled the RPG-43 projectile a few days ago (mostly for real armour penetration functionality), I came to the same conclusion and switched the explosion sounds to use the panzerfaust explosion sounds. They are used by all the HEAT rockets/bombs for infantry AT weapons. It's a similar HEAT charge exploding, just having been thrown instead of launched. Will serve much better until a unique sound is available.
