### ISSUE TITLE
Brecourt can be made unwinnable if the Axis satchel Gun 3 or 4 before they are active

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#639]

**Comment by AndrewTheel** [comment]
Okay I'm attempting a proper fix for this.  I've always wanted to implement the fix for this bug, but a proper fix requires an override of the RODestroyableStaticMesh (which we have).  However, I have to implement a check in the TakeDamage() function that will the instigator of the damage.  I'm doing a few tests to see if I can get some progress on it.

**Comment by AndrewTheel** [comment]
Okay that angle of approach did not work out.  Instead I've come in from the ExplosiveProjectile angle.  So Satchels check what they are allowed to damage before they call the TakeDamage() function.  Fix coming shortly.

**Comment by AndrewTheel** [comment]
Should be fixed in commit: https://github.com/DarklightGames/DarkestHour/commit/e9e795b1afb0d3d3662dc7cdc3518718d2182494

**Comment by AndrewTheel** [comment]
As a note: DSMs can still be damaged by the team's tank shells, artillery, mortars, etc IF the DSM is setup to let that type of damage harm it.

In most cases DSMs are setup to only take satchel damage and probably should be as such.

**Comment by handsm** [comment]
I've re-opened this as:

1. I don't think we're tackling the underlying problem, which is that an destruction objective can be destroyed before it is activated, leaving it unachievable when it gets activated later - effectively breaking the map. This is a fundamental flaw and has wider implications that just Brecourt.

2. The new option to prevent damage by one team can be improved to work with other projectiles, not just satchels. Although this is a bit of a workaround to the fundamental problem, I think it's a good idea and a useful option to have. I imagine this option could have use in other situations, not just like on Brecourt, but where a leveler may want to prevent any kind of destro mesh from being destroyed by the 'wrong' team.

I'll commit a couple of revisions for everyone to look at.

**Comment by handsm** [comment]
First a slight optimisation by moving the logic further up the satchel function so if we're going to do nothing to the mesh, we continue the loop before doing an unnecessary trace. Minor - just doing this before the real stuff.

**Comment by handsm** [comment]
In commit https://github.com/DarklightGames/DarkestHour/commit/c67f3dc4d83cf2e533fdd0a79c416ac154069bfd I've used an alternative method to prevent a specified team from damaging a destroyable static mesh. 
@Theel when you 1st tried implementing this logic on the destro mesh's TakeDamage() function, I suspect you ran into the significant problem where the responsible player may have died. In which case there's no passed in Instigator pawn so the mesh can't tell who has done the damage. I think it's a bit of a fundamental problem in damage functionality.

But I think there's existing functionality we can use to solve that problem. When any kind of shell, explosive or rocket projectile causes explosion or impact damage, it first calls a snappily named actor function called SetDelayedDamageInstigatorController() on whatever they're about to damage. It's an empty function by default, but it was cleverly placed there allowing us to add a DelayedDamageInstigatorController reference in any class and use the function to set it. So basically it gives us a hook into any actor class before a projectile calls TakeDamage on it. And being a Controller reference, the useful feature is the DelayedDamageInstigatorController persists if its pawn dies or if the player switches pawn (i.e. enters/leaves a vehicle pawn).

So, I've implemented it in the DH destro mesh class, then we can use it for a simple team check in the mesh's TakeDamage(). I've used a GetDamagingTeamIndex() helper function to handle the team check - basically it uses the Instigator if there is one, but if not it uses the DDIC. The logic is all on the authority role so there are no server/client issues here.

The only problem we can get in these kind of situations (this isn't unique) is if the player changes teams or leaves the server. If he changes team his controller also changes team, which could allow unwanted damage to the mesh, & if he exits the server the controller reference becomes null. But this is exactly the same as with the previous method & anyway there is built in protection against changing teams in thrown explosives & something very similar in the arty shell.

I've written the logic so that it doesn't just check for the player being on the prohibited team, it specifically makes sure he is on the opposite team. That stops exploits by switching to spectate after throwing a satchel, for example. So really the new bDestroyableByAxis property could more accurately be described as bCanOnlyBeDamagedByAllies. Haven't renamed it though that as it would require a Brecourt edit, but it is a more logical and direct name. Better still would be to have a single enum property called something like TeamCanDamageMesh, with default value of Both & with options for Axis and Allies.

Overall, this method extends the team restriction to work with all kinds of shells and exploding projectiles, including protection against a player switching to spectate or exiting the server. So it is a way of improving & extending the team restriction option. It doesn't go any further in tackling the underlying problem, being that an destruction objective can be destroyed before it is activated, leaving it unachievable when it gets activated later. I'll add something for that next.

**Comment by handsm** [comment]
In commit https://github.com/DarklightGames/DarkestHour/commit/ba35b6d4643381579d0858f5026ccb7296d5adcd I've added a more fundamental fix. All I've done is added a bActive property in the DH destroyable static mesh class, paired with a bInitiallyActive option for the leveller (true by default). That is common in a range of actors, like objectives, spawn points & mine volumes.

I've extended the DH_ModifyDSMStatus level actor to include options to activate or deactivate a destro mesh, or toggle its active status. To make a distinction between toggle options I've renamed the existing DSM_Toggle option to DSM_ToggleDestroyed (doesn't affect any maps as it's just a text label for an enum numeric setting).

To implement the new bActive functionality, all I've done is add an early exit from the destro mesh's TakeDamage() function if it isn't active. So an inactive destro mesh simply can't be damaged by weapons or projectiles in game. It can still be destroyed by something triggering the mesh, like a DSM modifier.
I could easily prevent that but I figure it's extremely rare and basically part of the map design (i.e. set up triggers, events and actor properly).

There is no replication in this implementation as all the logic is on the server. It only needs bActive to be replicated if it is to be used in the HUD, which is probably should be, i.e. if a DSM is shown on the map (bShowOnSituationMap=true) then it should only be shown when active. I'll add that next - it's very simple, the replication would only very rarely happen and would be negligible, and a displayed DSM 'target' would be odd if you couldn't then destroy it as it's inactive.

This active/deactivated DSM functionality isn't intended to replace the earlier team damage restriction option; it probably sits alongside it in many cases. Using Brecourt as an example, even when guns 3 & 4 become active it's still better to stop an idiot/griefer German player from destroying them and losing their own team's defensive objectives. So that idea is till very useful and still better to retain the 'only allies can destroy guns' set up.

And with those guns starting initially deactivated and only become active later, it also stops a US player from being able to destroy guns before their objectives are active, so breaking the game. In Brecourt that is avoided by using a mine volume, but in another map/situation that may not be the case.
So think of this as all working in tandem.

**Comment by handsm** [comment]
I've added a temporary demo version of Brecourt with this new functionality implemented, just to show/test the new functionality in use.

All I've done is made guns 3 and 4 so they aren't bInitiallyActive, then added two modify DSM actors to activate guns 3 & 4 when guns 1 & 2 are destroyed. The DSM modify actors are triggered by the same event that triggers the existing modify (disable) mine volume actor. (Just to make it clearer, I renamed the triggered/triggering event from 'Deactivate_Gun3and4Prot' to the more general 'ActivateGuns3And4').

**Comment by handsm** [comment]
In commit https://github.com/DarklightGames/DarkestHour/commit/37e3d487cf9f96d7e958499e138d5c449cd21b0b, I've implemented the extra HUD functionality so if the DSM has been set to bShowOnSituationMap (as a destroyable target), it won't be shown if deactivated.

**Comment by AndrewTheel** [comment]
Wow great changes.  

I tested the demo and tried everything I could think of to grief the guns as Axis with no prevail.  Go ahead and replace Brecourt with the demo, fix any variable names you desire, and thanks for a proper fix for this issue.  The issues surrounding the DSMs are finally gone, I'll probably be more keen to use them in maps now!

BTW, I eventually want to create vehicles that are objectives and cannot be griefed by their own team.  So we can have "hunt" the Tiger type of scenarios.

**Comment by handsm** [comment]
OK, that's great. In commit https://github.com/DarklightGames/DarkestHour/commit/a6348c78e6aaa867f8dc0d6ec21132a944718b1c I've made the changes, updated Brecourt and deleted the temp demo map.

I've replaced bDestroyableByAxis and bDestroyableByAllies with a single TeamCanDamage enum. It defaults to the enum zero value of 'both', but leveller can specify the mesh can only be damaged by allies or axis.

Changes to Brecourt:

- Set all four gun DSMs so they can only be damaged by the allies.
- Set guns 3 & 4 to be initially deactivated.
- Added two DSM modify actors to activate the DSMs for guns 3 & 4 when guns 1 & 2 are both destroyed.
- Renamed the event that is triggered when guns 1 & 2 are both destroyed  from 'Deactivate_Gun3and4Prot' to 'ActivateGuns3And4' to be more generic.
- Full rebuild with lighting to RGB8.

 I've run through the map and all seems to behave as desired. Germans can't satchel any gun at any stage. US cannot satchel guns 3 or 4 in the earlier stage, but can later. Map progresses through objectives and is won when US destroy all four guns.

**Comment by handsm** [comment]
@Theel : If you may use destroyable objectives more then one other thing I also considered was to make a combined actor, or at least build in the functionality without having to use separate events and modify actors.

Ideally we would have a single 'destroyable objective' actor, combining the functionality of the objective with the DSM. It would have to be an objective, so would need to build in DSM functionality. But not only is there a fair bit of that, but various areas of code specifically look for a DSM actor, so a single actor like that just cannot work & I discounted that.

But nearly as easy to use would be to have an objective that includes the option of a reference (via a matching, leveller-specified Tag name) to a linked DSM, so the DSM is activated/deactivated in sync with the objective. Could just add that to the standard objective class, but I felt it was a bit obscure.

I concluded that if you feel this sort of actor would be useful and worth adding, it should be a subclass of objective - say called DHDestroyableObjective. It would add the linked DSM (as a requirement) and would also include standard default properties required to set up this kind of special objective, i.e. make it so it can't be captured in the normal way (just Radius=0?). To reduce cross-dependency in setup, it could either find its DSM by looking for a DSM with a DestroyedEvent matching the objective's own Tag, or it could set the DSM's DestroyedEvent (in begin play) to automatically match the objective's Tag.

Minimal work required. Think it may be useful?

**Comment by AndrewTheel** [comment]
I don't really see a need, you can already tie a DSM to an objective quite easily.  Adding it will make a leveler have less actors to deal with, but more actors to deal with for us.  Unless it offers some new ability that cannot be achieved with the 2 actor method, I'd say not to bother.

**Comment by handsm** [comment]
Fair enough. Issue closed.
