### ISSUE TITLE
Weapon Pickups don't have a "no respawn" setting

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#656]
Weapon Pickups don't have a no respawn setting, instead the leveler has to choose some high arbitrary number for the respawn time.  This doesn't seem optimized as the pickup doesn't need to be running logic if it is intended to only spawn once.  Perhaps the default should be only to spawn once as that is most of the time the intended desire for a weapon pickup.

**Comment by handsm** [comment]
Yeah, fair points. Even though the running logic is only a state's Sleep() timer, I guess native code is still having to tick that up towards some far distant time it will never reach, so there's no need for even that,

The best way to do this would be to make it so that a RespawnTime of zero means no respawn. That avoids adding an extra bool variable (e.g. bPickupRespawns) and, importantly, it is consistent with lots of other leveler-optional functionality, where a zero value means it does nothing and you specify a 'real' value to enable the functionality.

But I think we need to leave the default as it is, because otherwise it will break community maps that have a placeable pickup using the current default (60 second) respawn. As they have no override value, they will suddenly inherit the new zero value and no longer perform as intended.

**Comment by handsm** [comment]
Implemented in commit https://github.com/DarklightGames/DarkestHour/commit/8ec5058439d90e34acd90f63726f9609f61f0a0c.

**Comment by AndrewTheel** [comment]
It works, makes sense, and does the job I wanted more or less.
