### ISSUE TITLE
Log spam on Flakturm Tiergarten

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#658]
The server log gets spammed with dozens of this exact message on Flakturm Tiergarten. It's gotta be something to do with the random artillery that is falling.

```
Warning: ROTankCannonShell DH-Flakturm_Tiergarten.ROTankCannonShell (Function ROEngine.ROBallisticProjectile.PostBeginPlay:0041) Accessed None 'Instigator'
Warning: ROTankCannonShell DH-Flakturm_Tiergarten.ROTankCannonShell (Function ROEngine.ROBallisticProjectile.PostBeginPlay:0049) Accessed None
```

**Comment by handsm** [comment]
Caused by ScriptedTrigger38, set up to spawn an ROTankCannonShell actor, which happens to include that accessed none flaw. The RO shell actor is deprecated in DH switching to the direct DH equivalent means changing it to spawn a DHCannonShell, which would remove the log spam and be generally more compatible with our game. But as this is an AP shell and it's meant to be simulating random arty, I suggest using either DHCannonShellHE or a specific HE shell class. I'd go for a specific class so you know what size of explosion you're getting.

A quick change and so small I suggest we do it for the 7.2 release.

I'll search for other typical defunct RO classes that can be lurking in actors like these, especially in converted RO maps. You can do a text search through the .rom map files, which reveals them.

**Comment by handsm** [comment]
Similar on a western front map: St Clement has ScriptedTrigger0 spawning an ROArtilleryShell, which needs switching to DHArtilleryShell.

**Comment by AndrewTheel** [comment]
Working on these

**Comment by AndrewTheel** [comment]
Flakturm Tiergarten's "random" artillery isn't "artillery" it is for the effects of the flak tower being pounded, but it doesn't work anyways.  I'll just remove them for now and if we ever want to add in the effects of it being shelled we can add it, for now better to not having something than to have something broken.

**Comment by cmbasnett** [comment]
Can we close this one?
