### ISSUE TITLE
Log spam when firing SdKfz 234/1

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#659]
```Warning: SpawnActor failed because class DH_Sdkfz2341CannonShellMixed is abstract```

**Comment by handsm** [comment]
Baffled!. The firing code in the 234/1 cannon class, show below, is overridden so it will never try to spawn the PrimaryProjectileClass, which is just a dummy class used to signify it needs to alternate between the secondary (AP) and tertiary (HE) projectile classes. It's been this way since DH 6.0; no recent change. I've fired thousands of 20mm mixed mags since then, always with a client and server log shown live on a second screen, and I've never seen this.

Have you seen this regularly or just once? I'm assuming it was on the server log, as the VehicleWeapon Fire() function (and the SpawnProjectile() function) are server only.

```
// Modified to alternate between AP & HE rounds if firing a mixed mag (the tertiary ammo type)
state ProjectileFireMode
{
    function Fire(Controller C)
    {
        if (ProjectileClass == PrimaryProjectileClass)
        {
            if (bMixedMagFireAP)
            {
                SpawnProjectile(SecondaryProjectileClass, false);
            }
            else
            {
                SpawnProjectile(TertiaryProjectileClass, false);
            }

            bMixedMagFireAP = !bMixedMagFireAP;
        }
        else
        {
            SpawnProjectile(ProjectileClass, false);
        }
    }
}

defaultproperties
{
    PrimaryProjectileClass=class'DH_Vehicles.DH_Sdkfz2341CannonShellMixed'
    SecondaryProjectileClass=class'DH_Vehicles.DH_Sdkfz2341CannonShell'
    TertiaryProjectileClass=class'DH_Vehicles.DH_Sdkfz2341CannonShellHE'
}
```

**Comment by cmbasnett** [comment]
Yes, it was in the server log. It seemed to happen intermittently, not necessarily every time it was fired. Is it possible that something *else* is trying to spawn the `PrimaryProjectileClass` outside of the usual logic?

**Comment by handsm** [comment]
I want to say no, but logically it seems like it has to be yes! You've seen that code above and there's no way that could try to spawn the PrimaryProjectileClass.

**Comment by cmbasnett** [comment]
Just had a thought, could it possibly be in some other state other than `ProjectileFireMode`? Perhaps the `global` `Fire` function is being called that falls back on the old functionality.

**Comment by UnrealG0bl1n** [comment]
roflmao!!!

**Comment by handsm** [comment]
Not the global function, as that only logs a "tried to fire out of state" error. But that line of thinking did put me onto the problem, which is state related. A few different ways of fixing, but will update when I've had chance to check out the pros and cons. Cheers.

**Comment by handsm** [comment]
I'd added a ServerCeaseFire state for vehicle weapons, extending state ProjectileFireMode, which was needed to solve a specific issue. It just adds a split second delay on a server before resetting a replicated variable, giving time for the current value to reach clients before sending them the reset/zeroed value. It makes use of a state's latent Sleep() function.

If the player presses fire again almost immediately, within the split second the vehicle weapon is in the new state, it goes back to ProjectileFireMode immediately and calls the super Fire() function from that state. Note that super here means super state and not the usual super class. It works that way mostly, but there is a problem with state inheritance that gets discussed neat the bottom of this page ("There's a catch with behaviour of extended states when a base state function in subclass is overridden"):

https://wiki.beyondunreal.com/Legacy:Extending_States

The 234/1 cannon overrides the Fire() function in ProjectileFireMode. So it seems that when it is in state ServerCeaseFire, the call to the state super Fire() function becomes a call to the class super function. That results in the standard fire functionality, which spawns the current ProjectileClass, where the 234/1 needs to use its own Fire() functions that for a mixed mag alternates between AP and HE rounds.

This problem would actually cause the 234/1 to fail to fire although only momentarily. It also affects the flakvierling and M45 quadmount, but in less obvious ways.

I considered three options to resolve or work around this:

1. Re-state the ProjectileFireMode state in each vehicle weapon that overrides the Fire() function. Rejected as very messy and also anyone having to override Fire() in some future class will most likely run into this problem without knowing it.

2. If the player fires while in ServerCeaseFire state, set a bPendingFire flag (an instance bool) and add a BeginState() function in ProjectileFireMode that says "if bPendingFire is true then call Fire()". So pressing fire sets the flag, flips the actor into ProjectileFireMode and the startb of the new state makes it fire. Tested it and it works. Think we'd need an equivalent flag for alt fire. It's an ok solution, but a bit too much intervention as a workaround.

3. Scrap state ProjectileFireMode. In UT2004 vehicle weapons either live in that mode or InstantFireMode. They enter one or the other as soon as they spawn and that in that state forever. RO and DH only ever use ProjectileFireMode, as InstantFireMode is only for irrelevant weapons like a laser. I have previously emptied out the InstantFireMode functionality as irrelevant and effectively deprecated. The two states only have differing Fire() and AltFire() functionality. They don't make use of any special state functionality and no other classes reference or check a vehicle weapon's state. The states serve no real purpose, even in UT2004.

So I'm going with option 3 and scrapping ProjectileFireMode. It cleanly solves this problem, prevents any related recurrence with any future developments and strips away some redundancy. And I especially like it because it strips away a 'layer' of perma-states that make it harder to implement other states for different purposes. So in any future functionality it will be very easy to use states as vehicle weapons will now exist naturally outside of any special state. And for a vehicle weapon I can imagine the ability to enter temporary states could be very useful.

**Comment by handsm** [comment]
Fixed, as described above, in commit https://github.com/DarklightGames/DarkestHour/commit/be1a301fd34e0b93fc685b62e28d7ff86dbaaabf.

ProjectileFireMode deprecated and the Fire() and AltFire() functionality that used to sit within it are now just the normal non-state functions.
