### ISSUE TITLE
Kick votes should not be made anonymously

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#666]
Players abuse this and it's very distracting. Simply naming the dingus who's doing it should dissuade people from abusing the system.

**Comment by AndrewTheel** [comment]
has placed a kick vote against Colin Basnett.  

Get him outta here before he destroys everyone's abusive compulsions!

**Comment by dynamittt** [comment]
WebAdmin(Defaults)>KickVoting>tick Enable Kick Voting> click 'Accept'.

This is a server setting and its up to server admin to enable or disable anonymous kick voting. Why rob server admins from ability to set up the server to their preference?

And what's 'abusing the system'?  Its up to the server admin to set a reasonable kick percentage.
If he set up a very low value, and players get kicked relatively easy, or he set up unreasonably high percentage (trolls, abusers etc. etc. never get kicked even though they receive plenty of kick votes)
then he is the one to be blamed.
 
Throughout the years I found out that 31 percent is the perfect value. 50 percent is way too big, as most players don't know how to kick vote or don't bother doing it, except if the abuser is on their own team or trolling them directly.
A player must be able to be kicked by way less than the half of the people playing on the server(1/3 less or similar), since this is a team game, and most of the times abusers sabotage the general team-play and game balance in favor of one of the teams. I know this from personal experience while admining and playing on servers where the percentage of kick voting was set to 50 percent or above: abusers almost never got kicked, so we had to play with them.
And please note that if there is no good admin present at server peak-hours, no automated system, code or math can replace the human eye and brain.

last but not least: why is the anon kick info message wrong: "has placed a kick vote against Colin Basnett."

instead of "**A kick vote has been placed against Colin Basnett.**" ?????

a simple check shows us this: Class XVotingHandler

lmsgAnonymousKickVote="A kick vote has been placed against %playername%"

**Comment by cmbasnett** [comment]
@dynamittt We're not talking about the percentage. I'm talking specifically how players can run down the entire list and post kick votes against every player, all entirely anonymously. I can confidently say that I've never seen a kick vote *ever* work in our game. The only time I've ever seen it used is to annoy people or give people they don't like a virtual "thumbs down". It just clutters the chat and causes a distraction.

Also, @AndrewTheel was joking, that's not the string. Take a load off.

**Comment by AndrewTheel** [comment]
TMK and I'm sure someone from the 29th can confirm this.  The 29th server actually had to remove vote kicking or raise the value past 50 percent as it was being abused.  Basically 3 or more guys would get together and kick everyone who joined their server so it'd never get off the ground, basically killing DH for the day.

Personally I think it is a relic of a system that's purpose is near pointless as it never passes when the reason is valid and is abused by trolls with invalid reasons.  Until the kick vote is team based and pops up for everyone on the team with F1 'Yes' and F2 'No' the system is pointless.  Also if its not already the kick should be a session ban, not just a kick.

**Comment by dynamittt** [comment]
> Until the kick vote is team based and pops up for everyone on the team with F1 'Yes' and F2 'No' the system is pointless

OK, what if someone is trolling the opposite team by using a bug, exploit or doing something else to gain advantage over them or to ruin the game balance? Why the players from the opposite team should not be able to vote kick him?

> Also if its not already the kick should be a session ban, not just a kick.
It is. (xVotingHandler, line 1339)

Please don't get me wrong, admin can't just leave the server alone all the time and expect that it's just going to take care of itself on its own. Sometimes you have to be smarter than the abusers, use random nickname, join the game instead of simply staying in spectators for 40 minutes, pretend you are just playing while actually paying attention to suspicious players and so on...
The most common situation (caused by poor admining) is: Abuser trolls and abuses the game. Later admin shows up (in his typical manner, using his known nickname, and so on). Abuser sees this, and immediately changes his nickname, or leaves and reconnects using different ID and starts playing normally as if nothing happened. Later admin leaves and trolling starts again....Meanwhile someone gets admin-kicked for trying to move the MDV closer to the cap zone.

_All of the above is simply my personal opinion based on my personal experience._

**Comment by AndrewTheel** [comment]
Anonymous kick voting is a server setting, the server needs to turn it off.  I've made the new default in the default.ini to be off by default.  

Kick voting is entirely and absolutely pointless though.  Here is why:
1) The default vote kick percentage is 51%, meaning you need 51% of all the players on the server to vote to kick an individual.  With a full 64 player server that is 33 votes, which will NEVER happen.

2) Turning the vote kick percentage lower is extremely broken, as anything lower than 33% will result in 1 guy being able to kick everyone out of the server constantly so it can never populate.

3) They can just come back each time if they are vote kicked.

That is why it needs to be team based, a session kick, and well completely rewritten.  I'd recommend for a server just to turn off kick voting as its more destructive than helpful in 100% of cases.
