### ISSUE TITLE
Vehicle fire system is always a death sentence and holds little value to the game 

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#673]
The vehicle fire system as it currently stands is a guaranteed execution for the vehicle.  The fire spreads near instantly or within less than 2 seconds and then no matter what the vehicle will be destroyed within 15 or so seconds.   

From my understanding this hold some value as to actually destroy a tank that has been damaged to the point no one would want to operate it and the player would rather just respawn with a new tank.  Actually from a gameplay point of view I'm sure most veteran tankers, especially on large tank maps, just stay in the tank on fire because there is near-zero reason for bailing.

Kashash brought up an alternative purpose to the fire system, which would make it more effectual and interesting from a gameplay standpoint.  

A) The fire system does not spread even close to as fast as it does now (perhaps no spread at all)
B) Any position on "fire" cannot be operated (instead it is assumed the crewman is extinguishing the fire)
C) Driver position is very unlikely to be on fire (perhaps no fire on the driver position)
D) Fire will extinguish itself after some time as long as a crewman is present on the position
E) The fire shouldn't do damage to the player unless driver or all positions are on fire (at which point the tank is in fact screwed)

The idea here is that a tank with a position on fire (especially the turret/gunner) will need to reverse out of combat as it is not currently combat effective, but COULD be again given enough time and if the tank can get in cover and not take another penetrating round.  This is a great idea to me because:

A) It doesn't remove the current purpose of the fire system (a position on fire left uncrewed for a while the fire will spread and then it will take damage over time or whatever)
B) It makes tanks just a bit more survivable
C) It creates a situation where it is advantageous to retreat (which IMO we need more of)
D) It won't harm large tank maps (to my knowledge)
E) Will be a step towards the "Tanks Shouldn't Always Explode" system
F) It actually makes sense (at least to me)

Anyways, I think this should be discussed a bit before we even consider it.  We need Matt's opinion on it and perhaps this system hasn't considered something Matt has.

┆Issue is synchronized with this [Trello card](https://trello.com/c/1zolIgiD)

**Comment by kashash** [comment]
Yes the similar thing is in Squad where players often withdraw the vehicle from combat when it gets hit and temporarily is on fire until some time when it gets extinguished. I believe the Iron Front 44 mod for Arma also had similar system where the tanks didn't instantly blow up but the tanks being rather ineffective and in a "knocked out" state after the git.

The survivability of tanks in DH is indeed way too extreme where the tanks are completely blown up when they're destroyed. It doesn't mean though that with this implemented the tanks will be harder to destroy, since the tank gunner position that is on fire will be inoperable meaning the tank is then ineffective to use until some time when the fire is extinguished. That gives some chance for the tank to survive if they won't receive another hit to the tank and manage to reverse to the safest spot.

Similar thing is in Graviteam Tactics Mius where a tank that has been hit and is on flames reverses back rather than explodes. A crew could either stay in a tank hoping they won't receive another hit and in hope it will recover, or bail out the tank. And this system would be the upgrade to the current hit the tanks until it explodes issue that it is now slightly archaic. Again when the tank is on fire, it virtually makes the tank ineffective as the crew cannot operate the gun and can only reverse so it is same as if the tank was basically put out of action.

**Comment by kashash** [comment]
The latest Squad update has one of the following:
"When a Heavy Anti Tank (HAT) directly hits an Armored Personnel Carrier (APC; Stryker, MTLB, BTR variants) it will no longer instantly blow up. The vehicle will burn up and be destroyed, but now the crew and passengers has a chance to get out and fight through the ambush."

It'd be nice to have something like that in DH.

**Comment by cmbasnett** [comment]
I'm in agreement with the spirit of this suggestion. Vehicle fires behave as a total death sentence to the tank, and they spread unrealistically fast, as though the whole interior of the tank was coated with kerosene. I would like to see, (at the _very_ least) a significant drop in the chance of fires being started _and_ decreasing the speed of fires being spread drastically. Right now the fires are ubiquitous, if your tank isn't instantly blown up in one shot, there's a 90% chance that the vehicle is now on fire and will be dead in about 2 seconds.

**Comment by AndrewTheel** [comment]
Decided against doing this, instead I want to lower the odds of fire if there are crewman in the vehicle and of course 100% chance of fire if the vehicle is empty.
