### ISSUE TITLE
Players should be able to change the loaded tank round type without firing the cannon

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#677]
Brought this up because it's been requested countless times.

The proposed functionality would be that the user would simply press the reload button to clear the breech and load a new round of the selected round type.

┆Issue is synchronized with this [Trello card](https://trello.com/c/0t8gxLhO)

**Comment by handsm** [comment]
Removed from v8 milestone as there are a number of issues to be considered here and the changes aren't simple or straightforward.

Unloading a shell must take at least as long as loading one, perhaps more as I imagine it's an awkward job. I imagine you'd have to then carefully re-rack the shell. All this must be done before you can think about loading the new shell. So if loading a shell takes say 6 seconds, it's going to take you 6 or more seconds to unload, then the usual 6 seconds to load the new shell.

In summary, you'd only ever want to unload a shell instead of firing off the unwanted, loaded type if you needed to (1) avoid firing and giving away your position, or (2) conserve ammo. You wouldn't do it because it was quicker - firing off the loaded shell is always going to be much quicker.

So my gut feeling is that an unload option is going to need a 'backwards' load, with the usual 4 stages and sounds, with the HUD's red loading stage also running backwards until it turns fully red again, meaning the shell has been fully unloaded. THEN you can start a conventional load, either manually after selecting a new round type (if you use the manual reload option), or automatically having earlier selected the new round.

Main change would be the timer functionality altered to work forwards or backwards. Not a problem, but not for v8 either imo.

**Comment by shiftycats** [comment]
Implemented.
