### ISSUE TITLE
Tank commander should be able to lock the tank except for the seat 3 mg bow gunner.

### ISSUE THREAD

**Issue by kashash** [DarklightGames/DarkestHour#678]
Let's face the fact. Most people don't want random players jumping in and taking over the gunner or driver position without even asking. It has ruined many rounds on many maps Too many times random players rudely come in the tank without even asking or refusing to leave while driving the tank like crazy.

The proposed idea is not to completely lock the tank for other crewman, but so that a crewman can still enter the tank but into the seat 3 MG bow gunner. Then the tank commander can grant the permission for the crewman to either drive/gun.

I'm sure the other crewman will be then more compliant to his orders rather than assuming that someone spawned the tank especially for him to get into the gunner/driver position so he can do whatever he wants.

┆Issue is synchronized with this [Trello card](https://trello.com/c/gBS0Knyc)

**Comment by cmbasnett** [comment]
This is a great idea. We already have a way for the user to be prompted to accept/reject with `F1` or `F2` keys via `DHSquadInviteInteraction`. We could make that style of menu functionality more generic, and easily create a prompt that looks like this:

    [DH]Basnett is requesting permission to operate your vehicles
    [F1] Accept  [F2] Reject  [F3] Block

**Comment by AndrewTheel** [comment]
The only (slight) problem I foresee with this is on a map where there is 1 tank available and 3 crewmen.  One guy could be locked out completely.  However, we can just edit those maps in question.

The other system we thought up would be to have each crewman role get his own tank no matter what.  For instance, if there are 2 tank crewman roles on a team that team gets 2 tanks active at once.  However, up to 2 players may join each crewman if he lets them in his squad.  They can't spawn the tank, only he can, but they can crew it.

We should consider how we could do something similar for DVs also.  The other day I parked the perfect DV, some guy spawned in it after 30 seconds and drove it to run me over and get it killed... this happens all the time.

What happens if the original spawn-er of the vehicle dies?
If the tank unlocks I think that is fine, but for DVs it makes little sense as most of the time he is going to die and then it'll be moved by some idiot anyways.

Perhaps the best idea is to leave public DVs how they are, but we can create squad vehicles which can only be crewed by members of that squad.  Yea lots to consider here.

**Comment by kashash** [comment]
3 crewmen is severly detrimental for just 1 tank available. 3 men just sit in a tank and usually only 1 guy actually shoots at the enemy, the other 2 just wasting a valuable slot which would be more useful as an infantry. And when there is only 2 crewmen then they usually swap around one time he's driving and gunning and other time just an MG gunner or attacking on foot along with infantry as most of the time, extra crewman in a tank is often useless.

**Comment by AndrewTheel** [comment]
Yea I agree for the most part, but can be fun if you got 2 friends

**Comment by AndrewTheel** [comment]
Okay so lets make this change only affect Advance maps and not mess with our Push maps.

**Comment by kashash** [comment]
I personally think this should be for the whole game, as this has been for the most part requested from players during the push maps so I doubt anyone would be missing of how it was before if this locking feature was implemented. But so be it if that's how you think it should be, because it would be good to even have that feature at all.

**Comment by handsm** [comment]
Just a quick note to say I've finished a system for locking tanks (& other armored vehicles), which I expect to commit tomorrow. I just some time to merge it with the latest code and write it up. I'll give a better explanation then. Cheers.

**Comment by AndrewTheel** [comment]
You said armored vehicles, can it be done for all vehicles, including jeeps and kubels?

**Comment by handsm** [comment]
Implemented a pretty comprehensive system in commit https://github.com/DarklightGames/DarkestHour/commit/681b7090c13e0fa35d28568a725c4748928e6116.

PLACEHOLDER -run out of time today, so will write up properly tomorrow.

**Comment by handsm** [comment]
This has been implemented and works, so just need to write it up and will then close the issue.

**Comment by AndrewTheel** [comment]
Closing this as it has been implemented, separate issues can be created for issues/bugs with it.
