### ISSUE TITLE
Changing MG barrel does not bring you back into the correct FOV

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#679]
You have to be deployed to change MG barrel which means you are iron-sighted and have a FOV zoom, but if you change barrel you leave that zoom but then don't return to it forcing the player to redeploy the MG.

┆Issue is synchronized with this [Trello card](https://trello.com/c/UKWqgSG0)

**Comment by cmbasnett** [comment]
Fixed in commit b7931d6e2c2c537e93398bea55d222881e12c8c2.

The logic that splits the timer functionality up into two "parts" was using `FMin` instead of `FMax` when determining the wait time for the second half of the timer cycle. This meant that the second timer cycle would be abnormally short (0.1 seconds), which would end up circumventing the code that reset the FOV back to normal.
