### ISSUE TITLE
Burning vehicles can be heard from very far distances

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#680]
I wonder if the burning sound makes them basically always relevant if the sound is extremely far.

┆Issue is synchronized with this [Trello card](https://trello.com/c/Sf6m8qIt)

**Comment by handsm** [comment]
PLACEHOLDER - Investigated this. Will write up and commit some changes tomorrow.

**Comment by handsm** [comment]
Yeah, could do, although it's not a ridiculous distance and vehicles, especially tanks, are pretty big, important actors (even destroyed tanks) that are usually network relevant from a good distance away. But it is a problem with the UT2004 engine that it seems to have excessive ambient sound distances, at the point where there's no way a human ear would actually hear the hugely reduced volume, but the engine still registers it as audible and makes an actor net relevant solely due to that.

The specified SoundRadius (SR) for an actor's ambient sound is the distance up to which the sound is heard at full volume, not the maximum sound distance as some may assume. Beyond the SR the volume drops off. But the sound is treated as audible at up to a whopping 100 x SR, which in practice is way beyond the point where you can actually hear it!

A vehicle can have two types of burning sound and each currently has a different SR. When a vehicle is destroyed and burns, the SR is currently 600 Unreal Units, meaning it can - theoretically - be heard out to 60,000 UU, which is 994m. A tank that has been set on fire but not yet blown up has a slightly different sound with a SR of only 200 UU, which can be 'heard' out to 331m.

I did some testing of how the SR cut-off for ambient sound works over the network and it's as described. I put a burning vehicle behind a BSP wall, having stopped the code that would normally destroy it, so uit burned forever. Then I logged when the actor was destroyed on the net client because it was no longer net relevant. The actor drops out exactly on the specified 100 x SR distance, and pops back into being if you move back closer than that.

**Comment by handsm** [comment]
Experimented with SR values and in commit https://github.com/DarklightGames/DarkestHour/commit/9d3d37c9419441f76caa90dcbe26e5a2050ef8c6I've reduced the SR for a destroyed, burning vehicle from 600 to 300 UU, meaning the ambient sound will only make the actor net relevant out to a distance of just under 500m. It may be relevant for other reasons, such as you can see it and the map's distance fog doesn't cull it - but the faint burning sound alone won't force it to be considered net relevant.

Matched a tank's burning sound (when set on fire but not yet destroyed) to same SR, with a slight code change to make sure a dedicated server gets the same SoundRadius change when a tank is set on fire.

Burning sound volumes when in the vicinity of a burning vehicle sound natural, but the network relevancy implication of the ambient sound radius of a destroyed, burning vehicle is greatly reduced.
