### ISSUE TITLE
Mortars stay around after the operator is killed

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#682]
This can lead to many mortars in a map.

┆Issue is synchronized with this [Trello card](https://trello.com/c/daCJ2TQb)

**Comment by AndrewTheel** [comment]
I believe this is fixed for 8.0, but I don't think went into the live 7.2.3 update.

**Comment by handsm** [comment]
I meant to ask about this, as I haven't seen the problem and mortars (assume you mean deployed mortars) have always been destroyed after a 5 second delay when their player owner dies. Has any change been made in the dev build?

Just took a very quick look at the process to refresh my memory of it: in DHPawn's server function Died() it sends any owned mortar into state PendingDestroy, which simply sleeps for 5 seconds and then destroys the mortar (this is in the DHMortarVehicle actor, which is the base for the mortar component actors).

One possible problem is at the start of Died(), there is an immediate exit from that function if the DHPawn is flagged as bDeleteMe, meaning that actor is being destroyed. Normally I guess a DHPawn isn't immediately destroyed when the player is killed, because it becomes a ragdoll corpse for a while. But I wonder if in some circumstances the DHPawn is immediately flagged for actor destruction, in which case Died() exits prematurely, before it can set the mortar's 5 second self-destruct countdown.

There are some other things in Died() that could perhaps cause problems if the function exits without doing anything; things that should happen regardless of whether the DHPawn actor is being destroyed immediately. May be best to make sure this kind of functionality, including mortar destruction, gets triggered from either Died() or the DHPawn's Destroyed() event.

**Comment by handsm** [comment]
PLACEHOLDER - Have a fix. Will write up and commit tomorrow.

**Comment by handsm** [comment]
Ah ok, it's a bug in the live build - and I'm the culprit! :(  Although I tracked it down to something very, very weird and obscure.

The problem has been caused by setting Physics to none in a mortar vehicle's default properties. The 'vehicle' actor is just an invisible base for the mortar vehicle weapon actor, which represents the actual deployed mortar that you see, enter and use. Some time ago I changed the physics to none, instead o the default karma physics for a vehicle, to stop karma log errors that were caused because the invisible mortar base mesh had no karma collision (i.e. pink collision boxes) or karma parameters. The mortar operates normally with Physics none, but ....

But for some very strange reason that is beyond me, with debug logging I traced it to the fact that physics none appears to stop any state code executing! So state PendingDestroy, although it is entered, doesn't actually do anything, i.e. destroy the mortar after a 5 second delay.

**Comment by handsm** [comment]
Ah ok, it's a bug in the live build - and I'm the culprit! :(  Although I tracked it down to something very, very weird and obscure.

The problem has been caused by setting Physics to none in a mortar vehicle's default properties. The 'vehicle' actor is just an invisible base for the mortar vehicle weapon actor, which represents the actual deployed mortar that you see, enter and use. Some time ago I changed the physics to none, instead o the default karma physics for a vehicle, to stop karma log errors that were caused because the invisible mortar base mesh had no karma collision (i.e. pink collision boxes) or karma parameters. The mortar operates normally with Physics none, but ....

But for some very strange reason that is beyond me, with debug logging I traced it to the fact that physics none appears to stop any state code executing! So state PendingDestroy, although it is entered, doesn't actually do anything, i.e. destroy the mortar after a 5 second delay. It doesn't even log if you add a log command under the state's Begin: label. But it does enter the state and calls the usual BeginState() event - which will log just fine.

As a further test, I tried setting a 5 second timer in BeginState(). Logging showed that the timer had been set, but the timer didn't actually count down, it just stayed on 5 seconds for ever - similar to the lack of state code execution under the Begin: label. This is so weird; lots of other actors with physics none execute state code and run timers, e.g. vehicle weapons and weapon pawns. There is no documentation suggesting that state code or timers don't work without physics.

Anyway, in commit https://github.com/DarklightGames/DarkestHour/commit/626b83f23d898238132ef10d04176a8d5fd571a3 I've reverted the physics to the normal karma setting, which fixes this bug. And to resolve the original problem of the karma log errors in a different way, I've added a tiny karma collision box to the mortar base's mesh and some very basic karma parameters in default properties.
