### ISSUE TITLE
Round Timer should stop counting down once the match is over/won

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#685]
The round timer continues to count down once a match is over, making it hard to know exactly when it stopped and seems a bit odd.

**Comment by AndrewTheel** [comment]
Fixed in https://github.com/DarklightGames/DarkestHour/commit/5cc39f1f9551d3bcdb8372389e30eb143b537ae0

**Comment by handsm** [comment]
Tidied up and improved this in commit https://github.com/DarklightGames/DarkestHour/commit/fbb57f4a15e1f871c84f9cf7aec24b12cc7ff638.

The calculation and display of remaining round time is done in four different places - spectator HUD, scoreboard, overhead map and deploy menu. The new bRoundIsOver flag wasn't included in the overhead map remaining time display, so it could be confusingly different to other time displays. The calculation logic has ended up a bit different across these four areas, not always optimised, e.g. checking the same bool twice (minor stuff).

Rather than repeat the logic and have to maintain it across four places, I've added a static GetRoundTimeRemaining() function in the GRI class, so it's only in one place and other classes call the static function when they want to update time remaining. As it's a static function it could go anywhere, but it doesn't really belong in any one class (not one that jumps out anyway). I've put it in the GRI as all the remaining time calculations use GRI properties.

**Comment by AndrewTheel** [comment]
Bug caused by these fixes reported here: https://github.com/DarklightGames/DarkestHour/issues/836 and has already been resolved.
