### ISSUE TITLE
Replace sound and textures with stripped down files on dedicated server

### ISSUE THREAD

**Issue by radanon** [DarklightGames/DarkestHour#699]
The dedicated servers for Red Orchestra and Mare Nostrum seem to use empty textures and sounds in their .utx and .uax packages. For example, Inf_Weapons.uax is 27MB in the regular installation and 22KB in the server. Looking in the packages it appears that the sounds and textures are still listed with their properties, but replaced with empty files. Using this method could save space and bandwidth for server installations.

┆Issue is synchronized with this [Trello card](https://trello.com/c/CcAJOwCo)

**Comment by cmbasnett** [comment]
This was done in a previous release, we even had it done automatically. However, there were problems with some of the files where the "stripping down" of the packages would fail on certain packages due to a bug with the `ucc` procedure. As a result we decided just to skip the stripping of the packages since it didn't make an impact on server performance.

I'll see if this can be reinstated for our upcoming release later this year. Thanks for your suggestion.

**Comment by compositebowman** [comment]
I'm not sure if this is the same problem you were having. I was able to use ucc datarip to successfully strip all of the textures and sounds in DH by temporarily adding these lines to RedOrchestra.ini
```[Core.System]
Paths=../DarkestHour/Sounds/*.uax
Paths=../DarkestHour/Textures/*.utx
```
Before that ucc wasn't able to find textures referenced in a separate file, so only independent files were being ripped. After the adding the paths all files complete with no warnings or errors.

**Comment by AndrewTheel** [comment]
You can also add -mod=DarkestHour to the end of the command to do that.
