### ISSUE TITLE
Floating bullet can be seen while crawling with the Lee Enfield Sniper Rifle

### ISSUE THREAD

**Issue by JCorrion** [DarklightGames/DarkestHour#700]
![afbeelding](https://cloud.githubusercontent.com/assets/27456324/26039108/b04872d4-3916-11e7-9f59-bd33debdafec.png)

On DevBuild.
Notice the little bullet on the right. It moves with the rifle while being prone. I respawned a couple of times and it was still there. First time I have ever seen it. Though I must say I never play as the sniper class so I dont know if this issue has been around long.

┆Issue is synchronized with this [Trello card](https://trello.com/c/0FLNjSFZ)

**Comment by cmbasnett** [comment]
This has likely been in forever, funny you mention it because I noticed this last night as well. It's a bug with the animation where they didn't put the bullet bone far enough away (or scale it down to 0) during this animation. Some brave soul might be able to export it out and fix this specific animation. Very low priority, of course.

**Comment by AndrewTheel** [comment]
Nope, this would be my doing.  I'm pretty sure I changed the FOV on this weapon along with others and just didn't notice as I didn't prone and crawl around.  The new FOV is better, would rather not change it back to what it was.  But we can if its that big a deal.

**Comment by JCorrion** [comment]
Considering that it will take a lot of work to fix I'd say leave it it. A charming bug we shall call it.

**Comment by cmbasnett** [comment]
Apparently this happens on the Springfield as well.
