### ISSUE TITLE
Switching to spectator from deploy menu in single player mode appears to crash map (but actually gets stuck on main menu)

### ISSUE THREAD

**Issue by JCorrion** [DarklightGames/DarkestHour#701]
When I'm in the class selection screen and click to go spectate, I get kicked back to the main menu while the map sounds are still playing. This has happened on Advance and non-Advance maps.

This does not happen if you go to spectate before selecting a team.

┆Issue is synchronized with this [Trello card](https://trello.com/c/SFpTahTm)

**Comment by cmbasnett** [comment]
Will look into this.

**Comment by handsm** [comment]
I've noticed this myself, without noticing this issue! Done some investigation over last couple of days and have cause and fix. Will commit fix today.

**Comment by handsm** [comment]
The bug only happens in single player mode and is not in the live release. Initially I thought it crashed you out of the game but, as Corrion says, the map is actually still running in the background and actually you are stuck on the main DH menu, with no way of getting back to the game.

The bug has been introduced in commit https://github.com/DarklightGames/DarkestHour/commit/a870c8e1fc936bf21b9d819172e9cd9e21b8d96b, as part of the new restrictions on team switching.

**Comment by handsm** [comment]
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/b2785fcfd73fd4651827a5b0784343b03f8533df.

The problem results from the additional "are you sure you want to switch?" window that is now opened. In engine terms, this is a GUI question page. When the player clicks 'yes' to switch, as part of the behind the scenes processes the CloseMenu() function gets called on the GUI controller to close the question page. From a lot of debug logging, I've found out that at this point (1) there is no other GUI page 'behind' the question page, as the deploy menu has been closed by then, and (2) in that situation the CloseMenu() function is coded to fall back to opening the main game menu unless the GUI page being closed is set to bAllowedAsLast. That bool, in the GUIPage class, means "if this is true, closing this page will not bring up the main menu".

Many GUI menu classes, including the deploy menu, have bAllowedAsLast set to true in default properties. The generic question page class does not. One solution would be to make a DH question page class, but I think only worth it if this problem crops up elsewhere. Since for now it appears to be a one off, I've fixed it by simply adding a line to set bAllowedAsLast when this specific question page is opened. That is enough to get the question page to close itself properly, using existing engine processes.

**Comment by handsm** [comment]
In commit https://github.com/DarklightGames/DarkestHour/commit/9c1ee6782e0d6f4d803c3cd728ddbb2de6f50c50 I've re-factored the new change team functionality in the OnClick() function and it's supporting ChangeToXXXChoice() functions, so it is standardised, much shorter and with less repetition.

I've added a useful helper function called OpenConfirmationWindow(), which opens a question page with a the desired message text, with the option of either a yes/no answer or a simple 'ok' to close the window. It can also pass back a reference to the question page if further settings are required, avoiding lookups and casting. In the deploy menu class it gets used prominently in the revised change team functionality and also in a couple of other places. This shortens and simplifies the code, increasing readability in this class.

It may be useful to make this helper function accessible to other GUI classes that are using question pages, by making it a static function and moving it to a more generic/central DH GUI class. But I'll consider that later; for now it's just in this class.
