### ISSUE TITLE
"Recommended" control scheme should be the default control scheme

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#715]
To improve the first-time experience (and first impression) of new players, the default control scheme should be something that a modern FPS gamer would feel comfortable with. The default RO binds are probably a turn-off for a large number of players.

I would suggest making the default control scheme identical to what is currently the "Recommended" control scheme.

**Comment by AndrewTheel** [comment]
Okay I've done this, will commit as soon as I can compile to test it.

**Comment by handsm** [comment]
We should discuss this. There are hundreds of players who have been using a configuration based on the RO default, probably tweaked to a greater or lesser extent, for many years. I am one of them - 11 years of use now. Forcing a change of default is going to annoy some of them - perhaps a lot and perhaps many of them. And without any need or particular benefit.

Choice of keys in entirely personal and are no better or worse than another, it's all just personal preference. I think we always have to be very careful that we're not pushing our own likes and dislikes on others. Terms like modern are a bit loaded, suggesting there's something wrong with players who prefer a key setup based more on the RO default. I don't think keyboard and mouse in a FPS doesn't change or evolve; it's nothing more than personal preference. We're all different. 

But what we can easily do is keep the two options, but make the description more descriptive and neutral. "Default" does kind of say "I am the norm, you should use me". Fair enough, I can understand that. And "recommended" is then kind of at odds with that.

So suggest we just rename default to something like "original RO defaults". Make it below recommended in the pick list if you like. But then people can continue to make their own choice and it's entirely clear what they are choosing. New players can be gently steered towards one route, but it doesn't need to remove choice and upset anyone.

**Comment by AndrewTheel** [comment]
Players that want a RO/DH classic defaults WILL HAVE a profile they can easily select to achieve.  Also this doesn't affect a player's controls unless they reset them, reset their ini file, or change profiles.  Which would likely affect their controls anyways.

I play a lot of FPS games and this new control scheme takes many controls from other games and maps them out very creditably.  As you say, every user is different and will likely remap them anyways.  However, our aim here is to have the defaults more creditable/reasonable based on a collection of "reasonable" controls from other games.  

Actually control schemes do evolve and there are expected standards.  For instance, no game other than RO has the talk key as Scroll Lock and no sane game has Aim Down Sights as MiddleMouse down.  Countless times new players ask, "Why are these controls so weird?" and then HAVE to change them.  If the default controls were more reasonable, they'd be less likely to change them, at which point we'd have more people using common controls.

We should not avoid making changes because we are afraid of how the community will receive it.  That is insulting to our community, basically assuming they can't accept new ideas.  That said, we do need to adjust ideas to make sure our community does perceive them well.  If they can't, then perhaps the idea is flawed and we should consider reverting it.  If we don't let our community try new ideas, then we are stagnant as a development team, which will eventually have players leave anyways.  

Much of this "change ideology" discussion is pointless though, as we don't force the controls, current players are only affected if they reset .ini or select default profile at which point they can spend 2 seconds selecting RO Classic control profile.

**Comment by cmbasnett** [comment]
This change should _only_ affect brand new players (aside from a couple of critical binds that *need* to be set (eg. `SquadTalk`, `ShowCommandMenu` etc.) . There should also be an "RO Classic" control scheme that can be selected for RO purists who like the original controls. This way, the vets are not affected, new players get a more familiar control scheme, and vets returning to the game (or reinstalling) have an easy way to get the old-school control scheme.

**Comment by AndrewTheel** [comment]
Yea and also we will have a prompt when the user launches 8.0 for the first time that shows the new default controls and asked them if they want to use them or keep their current.  With an added warning that there are new controls that will need bound/rebound.

**Comment by AndrewTheel** [comment]
Gonna close this as it is pretty much completed.
