### ISSUE TITLE
GMC passenger position has odd viewpoint

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#729]
Its just too low

![20170508000100_1](https://user-images.githubusercontent.com/16300108/27889885-049a0c32-61b5-11e7-8b2a-7b0a6709c8e1.jpg)

**Comment by handsm** [comment]
Unlike drivers, commander, etc, vehicle passengers don't have any camera position set up. The passenger pawn takes its camera position from the world location of the head bone in the player pawn model's rig. That's why the camera positions sways slightly, as it moves with the player's idling animation.

It's the same in every vehicle - the view position is exactly where the player's head is. The GMC passenger is pretty slumped, with his hands on his knees, so his head really is relatively low compared to the upright driver and some other vehicle front seat passengers. In the first screenshot below you can see his view point is more or less level with the middle of the side window, and in the second you can see that's where his head/eyes really are:
![gmcpassenger1](https://user-images.githubusercontent.com/16405443/28024714-6109827c-6589-11e7-9ee1-38ed63fcd268.jpg)
![gmcpassenger2](https://user-images.githubusercontent.com/16405443/28024713-60fc6830-6589-11e7-962c-41f857ef133d.jpg)

**Comment by cmbasnett** [comment]
Very minor, and when we eventually get a new GMC made this won't be an issue. Closing.
