### ISSUE TITLE
Add single-axis gyro-stabilizer to Sherman tank cannons

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#733]
One of the unique things about the Sherman tank was the single-axis gyro-stabilizer. It would be very nice to have this in-game! Suggested by [TheFurNinja](https://steamcommunity.com/profiles/76561193826652332).

**Comment by kashash** [comment]
It would be great if this was added, I'm in an accord of this idea of course. However just would like to state or advise the benefit of putting things before the other more urgent and important issues that actually have an effect on how the game acts and plays out. For example we were talking about the issue of tanks exploding too often, this to me is an issue that makes or brakes the game in one way or another. And even though I know that this isn't to be implemented for the 8.0 but more likely after 8.0, So because there seem to be so many little ideas, I just wanted to point out that it's good to prioritize things in order not to disrupt the workflow for the more important things that need fixing that have a huge impact on the way that game behaves rather than small features that aren't urgent. But there seems to be so many little ideas that aren't in an urgent need.

**Comment by handsm** [comment]
Have to disagree on this one. Firstly, the stabiliser wasn't very effective or even used much. While extremely clever technology for 1942-45, it wasn't nearly sophisticated enough to all firing on the move. What it did help was reducing the time to get the gun back onto target after moving. But only if crews used it. It was hard to use and maintain and few crews had the training and capability, so most accounts say most crews disabled it. It was certainly nothing remotely like a modern tank's gryostabliser.

Secondly, I can't imagine how this would be implemented or what change we'd see in game. What you see through your sights is based on where the gun is aiming in the game world. That's all handled by the game engine and native code. How can our script simulate a gyroscope and constantly adjust the pitch of the gun based on the up/down movements of the vehicle itself over the terrain?

**Comment by AndrewTheel** [comment]
I'm going to agree, this is out of the scope of the game and from my understanding it wasn't really a "game changer" to tank combat in WW2.
