### ISSUE TITLE
M16 halftrack's vehicle HUD icon is missing the turret and the red passenger dot for the gunner

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#738]
There are a number of problems with the M16 Halftrack's turret as a result of it not being a traditional tank cannon pawn (`DHVehicleCannonPawn`) and instead being a descendent of `DHVehicleMGPawn`. I will enumerate all the problems in this one issue since they are all seemingly related.

_**EDIT (Matt)**: These aren't actually to do with it being an MG. Issues 1 & 3 fixed and issue renamed. Issue 2 is more major and unconnected, so have logged as separate issue_ https://github.com/DarklightGames/DarkestHour/issues/872.

The problems start once you actually get on the turret itself.

1. Upon entering the vehicle as the driver, the turret is absent from the HUD.
2. Upon entering the cannon, the cannon will snap to face forward, even though it started facing backwards. This is obviously wrong, but I suspect it's a function of the MG "realizing" that it's rotation should be zero, setting it accordingly, thus instantly updating the rotation.
3. The red HUD dot that normally displays when you are on a turret disappears. I can't tell if it's being drawn over or just not being drawn at all.

This is currently affecting the M16 Halftrack's turret, and the lack of a red HUD dot is also noticeable on the M45 Quadmount static placements.

**Comment by handsm** [comment]
Issues (1) and (3) fixed in commit https://github.com/DarklightGames/DarkestHour/commit/4b9d41816a8f655c5ef309491514d41b5caee99d.

M45 quadmount previously had a DrawHUD() override to draw the turret icon, as the HUD only handles cannon turrets. That only shows for the gunner (issue 1) and it must draw over the top of red passenger position dots (issue 3). Neither was a problem for the M45 as it's a single position gun, but now it's mounted on the M16 halftrack it needs different handling.

I've added a simple change to the HUD functionality so it will now handle any turret, whether cannon or MG. This is useful anyway. Removed override in M45 as now redundant.

**Comment by handsm** [comment]
Issue (2) I believe is more fundamental and due to how native code handles a vehicle weapon attachment. May be worth a separate issue as I think unrelated and not connected with MG vs cannon.

I have experience of this before, when mounted a rear-facing 50 cal on a Jackson and Wolverine turret. Will look into it tomorrow.

**Comment by handsm** [comment]
Probably going to rename this issue to reflect problems 1 & 3, then close it as they have been fixed. Don't believe the bigger problem 2 has anything to do with this being an MG vehicle weapon and not a cannon. There's a big fundamental problem with vehicle weapons on a non-facing forwards base.

I believe vehicle weapon rotation is all handled by native code and it applies all rotation relative to the vehicle itself, regardless of which way the weapon is attached (i.e. the M45 turret attachment bone faces backwards, so the M45 starts facing backwards). As soon as a player gets in the M45, the native code takes over and that's what's making the M45 snap forwards, overriding the initial attachment rotation.

Not an easy one, I suspect. Think a solution will have something to do with setting an initial CurrentAim (in the weapon class) and/or CustomAim (in the weapon pawn class) when the vehicle spawns. Could be some issues there with vehicles replicated to net clients. Worst case scenario this may not have a solution and the fallback would be to attach the M45 facing forwards. Not ideal but not the end of the world either.

**Comment by handsm** [comment]
Issue 2 is more major and is unconnected, so have re-named and closed this issue (minor issues 1 & 3 fixed), and logged issue 2 separately as https://github.com/DarklightGames/DarkestHour/issues/872.
