### ISSUE TITLE
Shovel melee has a significant delay

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#766]
Swinging the shovels in melee does not hit when it should.

**Comment by cmbasnett** [comment]
This is because the animations are split incorrectly. They used to work but then someone went and overwrote it with broken animations. The problem is this:

Currently, the `bash_attack` animation plays the entire attack animation cycle which is incorrect. It needs to only play roughly frame 5 to frame 10 of it's current animation (the actual *attack* part of the animation)

The other problem is that `bash_return` is basically an empty animation, but it needs to be about frame 10 to frame 30 of the current `bash_attack` animation.

While we're at it, there are two missing animations: `crawl_in` and `crawl_out` (look at other properly animated weapons for reference on what this should look like!)

**Comment by cmbasnett** [comment]
Fixed in commits 3cf2711e and 5cd9cbb1.
