### ISSUE TITLE
Anti-tank guns are too difficult to enter

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#777]
We've all become accustomed to this over the years, but for new players and even some veterans (watching videos of them playing), a lot of people have difficulty "entering" the AT guns because of the extremely small and seemingly arbitrary collision box the player needs to be looking at in order to get the "Press [F] to enter <Gun>" prompt. Getting onto the guns should be made *much* easier!

**Comment by handsm** [comment]
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/d5555e95ad363e4d903ff94ee8ee04f47742ef3e.

Made it so the native auto-trace system, which registers certain actors if you are right in front of and looking directly at them, extends to vehicle weapons with collision, like turrets, AT gun cannons & some MGs. Or more specifically, in most cases it's the invisible collision static mesh actor that represents the vehicle weapon that gets registered by the auto trace. This extension of auto trace means you see an enter message when looking at an AT gun cannon/shield, and also a tank turret.

And I've extended ServerUse() in the PC class to handle the player looking at vehicle weapons or their collision mesh actors, as it now switches to the vehicle base and makes the player enter that.

I looked at this some time ago and the problem - showstopper - I hit was that even though a col mesh could be set to be registered by the auto trace, it didn't work because a col mesh actor is hidden (bHidden=true) and the auto trace ignores hidden actors.

Played around with a few things and got it to work by skinning col meshes with an alpha invisibility actor, so they were invisible but not actually bHidden. Effective but ugly, but gave me an idea to try setting col mesh DrawType to none - and that works just fine, hiding the col mesh while still allowing it to be registered by the auto trace.

Now very easy to get into AT guns!
