### ISSUE TITLE
Opel Blitz has wacky suspension that allows the wheel to go through the fender

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#826]
Perhaps adjusting the SuspTravel or SuspOffset would sort this out.

![20170916211321_1](https://user-images.githubusercontent.com/5035660/30517956-48e57a40-9b24-11e7-83a0-5e6594884970.jpg)

**Comment by handsm** [comment]
Leaving this as v8 milestone as I'll probably get the chance to fix it and I think it's something that could be done after a code lock, as a simple def props change and no affect on anything else.

**Comment by AndrewTheel** [comment]
This is not really related, but thought I'd say it anyways just in case it somehow is. I plan on revisiting the handling of the trucks as they are a bit wacky, especially with the handbrake.

**Comment by handsm** [comment]
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/337a8aa2c9c54206e08db6bd4a3c2afbc1a480c6.

Reduced WheelSuspensionMaxRenderTravel from default 15 to 4.5, which is the maximum travel without the front wheels bumping up through the fenders.

Have kept the related WheelSuspensionTravel at the default 15, as the two separate properties seem to imply that WST limits how far the suspension system/bone can travel in the physics engine, while WSMRT only limits how far the attached suspension parts/wheels are seen to travel. So retaining the original WST should mean driving is unaffected and limited WSMRT fixes a visual bug only.

But using the DrawVehiclePhysiscsWheels debug exec command suggests the wheel bones are limited by WSMRT (the debug exec draws spheres based on the current location of the wheel bones).
And if the wheel bones movement is 'clamped' by WSMRT, I wonder if there's actually any difference between the physics and visual limits, as I'd have thought the physics engine would be using the wheel bone positions. But hey, the visual bug is fixed.
