### ISSUE TITLE
Game crash (USkeletalMesh::GetCollisionBoundingBox)

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#835]
There's a strange crash that's been happening recently. Not much is known, but here are some common elements:

* Generally happens while driving a vehicle (possibly the Opel, specifically)
* Not map specific (happens on target range and other maps)
* Seems to happen while driving in third person mode only (though this might not have anything to do with it)
* Only encountered in single-player

```
Build RedOrchestraBuild[2005-11-27_10.48]

OS: Windows NT 6.2 (Build: 9200)
CPU: GenuineIntel PentiumPro-class processor @ 4004 MHz with 4095MB RAM
Video: NVIDIA GeForce GTX 970 (8541)

General protection fault!

History: USkeletalMesh::GetCollisionBoundingBox <- AActor::postKarmaStep <- PostStepAndDestroy <- KWorldStepSafeTime <- KTickLevelKarma <- TickAllActors <- ULevel::Tick <- (NetMode=0) <- TickLevel <- UGameEngine::Tick <- Level La Cambe <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 00000013 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free
```

**Comment by handsm** [comment]
Not sure this is new. Crash text looks like an occasional 3rd person view crash that has happened for years. With the areas I work on, I use vehicles a great deal and am often in and out of behind view. I get an occasional crash, which happens when switching into BV. Possibly when switching out of it too, but not 100% sure - but the crash certainly happens at the moment of switch, preceded by a split second freeze/stutter.

If it is the same crash then it isn't map or vehicle specific - and nor is it limited to single player. I get the crash in multi-player and it occurs on the client, so I just re-connect to the existing server game. I can't say for sure whether I've seen it in single player (sorry, it's an occasional nuisance that I've got used to). I think it does sometimes happen in SP, but I usually experience it in MP.

Originally I made it so you could use the BV toggle in SP and also in MP if running in DHDebugMode, i.e. in the dev build, unless debug mode specifically disabled. But due to these occasional crashes, I restricted it so it only worked in MP if the server had Level.Game.bAllowBehindView=true.  This was back in 2015.

Are you sure your reported crash only happens in SP? If you don't have bAllowBehindView enabled in your MP setup, you won't be able to go into BV so you can never encounter this bug. If your setup doesn't allow BV, suggest you enable it in your private MP environment and try it out. I suspect you'll see occasional crashes when switching to BV.

bAllowBehindView is a GameInfo config setting and I always enable it on a private or test server, but don't expect to see it in a public server. You can change it in your .ini file in the [Engine.GameInfo] section.

**Comment by cmbasnett** [comment]
Alrighty, not a problem, just wanted to make sure this wasn't going to start crashing servers once we release 8.0. Closing.
