### ISSUE TITLE
Unassigned players should not be able to spawn logistics trucks

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#842]
We should stop obvious lone-wolf trolling by requiring that a player has to be in a sufficiently full squad in order to spawn a logistics truck. Discuss in comments!

**Comment by AndrewTheel** [comment]
Please for the love of god, make it drive restricted also.  Also we should move all the vehicle lock code from armored to all vehicles. 

Reasons:
A) Players can still steal logistics trucks and other squad vehicles and drive them away to remote places
B) Someone in a squad can spawn the truck and purposely troll it

I don't have a great solution to B, because the player can easily join a different squad after being kicked. So even if he is kicked and not able to drive for a moment, he'll just join another squad and continue trolling. We could have a special case setup where if you are kicked from a squad you specifically get cast out of a vehicle and lose ownership of it.

**Comment by cmbasnett** [comment]
Implemented in commit 860c310c69c5a753392d34e153258db3a4499431.

Unassigned players can no longer spawn logistics vehicles. There's currently no conveyance as to why you're unable to spawn them, but it's not strictly necessary and that can be added later.
