### ISSUE TITLE
Locust turret scope texture has alpha smearing

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#878]
![20171022150254_1](https://user-images.githubusercontent.com/16300108/31866601-d1a7ca10-b747-11e7-8b21-12760a93fdd8.jpg)

**Comment by cmbasnett** [comment]
Assigning this to @handsm since he's working on the Locust. Notice the "smear" below the aperture? This happens because the texture is using clamping mode, but the edges of the texture are not pure black, so it takes this imperfection and smears it along that axis. The solution is to make sure all the pixels on the very outer ring of the image are a uniform black color.

**Comment by handsm** [comment]
Fixed in commit https://github.com/DarklightGames/DarkestHour/commit/b0459eeb4dc3e95284e52739d0643cd76f5d81cd.

Managed to add a very thin band of black along the bottom of the 'Stuart_sight_background' texture, which solves it.

@cmbasnett @ Thanks for the pointer.  :)
