### ISSUE TITLE
Add squad leader mutiny functionality

### ISSUE THREAD

**Issue by cmbasnett** [DarklightGames/DarkestHour#901]
Some people are really terrible squad leaders who don't know what they're doing. It would be handy to have some sort of squad leader mutiny option if the squad is large enough and enough people vote for it. It could trigger a vote for all the squad mates (squad leader excluded) that would need 75% approval to pass.

**Comment by AndrewTheel** [comment]
Was thinking, what if... if the SL hasn't placed a RP in 5 minutes, then it instigates a vote for the rest of the squad, which will allow them to vote him out of the squad completely (ban him from the squad).

**Comment by AndrewTheel** [comment]
Closing this as its a bit too complicated. Instead we will be doing another idea that is more easy to implement. Basically whenever someone leaves the squad, if the squad has no rallies AND one hasn't been placed in the last 5 minutes, the SL is kicked from the squad and others can volunteer (just as if the SL left the squad otherwise).
