### ISSUE TITLE
Players should be able to carry different types of grenades simultaneously

### ISSUE THREAD

**Issue by AndrewTheel** [DarklightGames/DarkestHour#943]
We've been wanting the ability to have multiple inventory in the "same" slot for ages.  The problem is we need a boolean that allows/prevents it on weapons. Meaning, you can't have 2 primary rifles for instance.

This can't be that hard to do, because it was a feature in UT2004!

**Comment by cmbasnett** [comment]
This would require some specialized logic, since we'd need to ensure that the total amount of grenades (across all types on that slot) do not exceed 3 (effectively undermining the in-class limit). Otherwise you could conceivably be walking around with 6 grenades if we simply just allowed the grenades to stack.

**Comment by AndrewTheel** [comment]
I'm fine with having like 12 grenades carried, it would be extremely hard to collect more than 6 grenades, and I'm fine with someone collecting so many grenades. TMK the Airborne for instance often loaded out with 8 grenades, so I don't see how 6 is all to terrible if hard to achieve.

**Comment by AndrewTheel** [comment]
Implemented in https://github.com/DarklightGames/DarkestHour/commit/8f6dd7b8dc001c522afa6a24d413a1a2fce88735
